### ISSUE TITLE
The Horror Channel tracker cannot be added

### ISSUE THREAD

**Issue by jpalenz77** [Prowlarr/Prowlarr#222] opened 2021-06-15 13:41 UTC
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
https://pastebin.com/aJQPAWcA

**Comment by bakerboy448** [comment] 2021-06-15 13:42
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/122

Please search prior to posting

**Closed by bakerboy448** 2021-06-15 13:42 UTC
Labels: Type: Bug

**Comment by jpalenz77** [comment] 2021-06-15 13:45
ups, sorry
