### ISSUE TITLE
Allow selecting multiple indexes at once

### ISSUE THREAD

**Issue by alculete** [Prowlarr/Prowlarr#1017] opened 2022-05-31 18:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

not related to a problem

### Describe the solution you'd like

Allow selecting multiple indexes when clicking on add index

### Describe alternatives you've considered

add checkboxes on indexes for selections 

### Anything else?

No

[AB#3215](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3215)

**Comment by bakerboy448** [comment] 2022-05-31 19:14
Duplicate of #407

**Comment by bakerboy448** [comment] 2022-05-31 19:25
Indexers have to be configured regardless, #407 was resolved by keeping the search/select modal up after adding an indexer

if you're adding much more than a dozen indexers or so, you're not getting any benefit and are presumably adding a ton of publics that scrape each other and only cause slower searches

**Closed by bakerboy448** 2022-05-31 19:25 UTC
Labels: Type: Feature Request, Status: Needs Triage
