### ISSUE TITLE
Sync Download Clients to services

### ISSUE THREAD

**Issue by JAP42** [Prowlarr/Prowlarr#1229] opened 2022-12-09 13:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No Problem, Just another feature to simplify setup of multiple services

### Describe the solution you'd like

Simply put, I would just like to have the download clients synced to the services. Entering data into every service is the biggest time suck for building and maintaining because we have to replicate our efforts 3-5 times for every service. Since we all ready add download clients to Prowlarr, why not sync them along with the indexers. 

### Describe alternatives you've considered

Alternative is just to manually enter Sabnzbd and Transmission to all 4 services I use, Up to 7 services currently supported for a total of 14 forms to fill out. Not including Prowlarr itself. 

### Anything else?

Thats it, simple idea, probably a nightmare to implement. Wish I was more help on that end, but I can ~~break~~ debug quite well. 

[AB#4384](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4384)

**Comment by bakerboy448** [comment] 2022-12-09 13:36
Duplicate of #1190

**Closed** 2022-12-09 13:37 UTC
Labels: Type: Feature Request, Type: Duplicate
