### ISSUE TITLE
[BUG]: Test all indexers does not work [fixed] | Indexer Statuses not updated for Test All

### ISSUE THREAD

**Issue by manderss99** [Prowlarr/Prowlarr#507] opened 2021-09-18 04:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when pressing test all indexers button nothing happens, no feedback and does not update the indexer statuses

### Expected Behavior

test all indexers, in sonarr it seem to work correctly

### Steps To Reproduce

add a few indexers and test by pressing test all indexers button

### Environment

```markdown
- OS: Ubuntu 21.04
- Prowlarr: Latest nightly 0.1.1.940
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: Chrome
```

### What branch are you running?

Nightly

### Anything else?

no

[AB#1592](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1592)

**Comment by Qstick** [comment] 2021-09-24 03:17
It works but didn't spin, that's fixed... The status updates are likely a different issue so I'll leave this open until I can investigate it

**Comment by bakerboy448** [comment] 2021-09-27 16:48
Spinning fixed in https://github.com/Prowlarr/Prowlarr/commit/40c49bce9b88f6e277b5524fa34356da0f5a9390

**Comment by JigSawFr** [comment] 2022-01-02 23:19
@bakerboy448 we should close this issue as fixed

**Comment by bakerboy448** [comment] 2022-01-03 00:08
The second part of the issue is outstanding, no?

**Comment by newadventure079** [comment] 2022-01-10 08:07
I pressed the Test all indexers button and it spun for about 30s and then stopped and no notifications were shown.  Did they all succeed? Did any fail? Was there supposed to be any status messages displayed?

**Comment by manderss99** [comment] 2022-01-16 07:38
> I pressed the Test all indexers button and it spun for about 30s and then stopped and no notifications were shown. Did they all succeed? Did any fail? Was there supposed to be any status messages displayed?

agree, need some feedback, suspect status updates not working

**Comment by bakerboy448** [comment] 2023-05-18 00:12
> Indexer Statuses not updated for Test All

Is this still an ongoing issue?

**Comment by bakerboy448** [comment] 2023-05-18 00:37
No status is given in any of the Starrs for Test of providers (indexers/lists/clients/etc.) though - so not a bug.

The status would be the fact that they either persist in the healthcheck or they tested successfully and are thus removed from the healthcheck.

**Closed by bakerboy448** 2023-05-18 00:37 UTC
Labels: Type: Bug
