### ISSUE TITLE
PassThePopcorn (PTP) Indexer flags not being displayed in radarr

### ISSUE THREAD

**Issue by Astonish3750** [Prowlarr/Prowlarr#1530] opened 2023-03-14 03:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Certain PassThePopcorn (PTP) Indexer flags are not being displayed in radarr, specifically these are "PTP_Golden" and "PTP_Approved". Where as "G_Freeleech" is being displayed correctly in radarr. These flags are being correctly displayed when performing a manual search within prowlarr, and they are also correctly displayed when using the inbuilt PTP indexer in radarr.

### Expected Behavior

I expect these flags to show up when using PTP synced to radarr.

### Steps To Reproduce

1. In a normal prowlarr setup
2. Setup PTP as an indexer
3. Setup radarr as an app
4. Sync PTP to radarr
5. Search for a movie that should display either "PTP_Golden" or "PTP_Approved" indexer flags
6. Observe how nothing is shown

### Environment

```markdown
- OS: Debian GNU/Linux 11 (bullseye)
- Prowlarr: 1.2.2.2699
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Microsoft Edge Version 110.0.1587.69 (Official build) (64-bit)
```

### What branch are you running?

Master

### Trace Logs?

Couldn't find any relevant trace logs

**Comment by bakerboy448** [comment] 2023-03-14 03:19
Duplicate of #51

**Closed by bakerboy448** 2023-03-14 03:19 UTC
Labels: Type: Bug, Status: Needs Triage
