### ISSUE TITLE
[FEAT]: Download clients sync

### ISSUE THREAD

**Issue by hrenard** [Prowlarr/Prowlarr#509] opened 2021-09-18 16:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I have to configure my download clients on every *arr (6).

### Describe the solution you'd like

I would like Prowlarr to sync my download clients too.

### Describe alternatives you've considered

- Doing it manually.
- Using NZBHydra2.
- Developing another arr.

### Anything else?

It expends the scope of the project, but it feels like the right place to do it.
It should be relatively straight forward to implement.

[AB#1595](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1595)

**Comment by bakerboy448** [comment] 2021-09-18 16:15
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/323

Please try to search better next time

**Closed by bakerboy448** 2021-09-18 16:15 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by hrenard** [comment] 2021-09-18 16:20
Too bad. Sorry for the duplicate.

**Comment by neo-neo1** [comment] 2021-11-06 05:05
Why sync indexers yet "no plans" for download clients? Isn't this the central efficiency prowlarr touts?

**Comment by bakerboy448** [comment] 2021-11-06 05:09
> Why sync indexers yet "no plans" for download clients? Isn't this the central efficiency prowlarr touts?

Prowlarr only uses Download Clients to send manual searched results to in Prowlarr. It’s not taking over your download stack, just indexer management.

you also typically only setup and configure a download client once nor replace them often if at all

**Comment by Panzer1119** [comment] 2021-11-07 20:40
I'm neither replacing my indexers often if at all.

It would be convenient to have these things in one place, even if it is just to temporarily disable a download client.

But there are more reasons why this could be helpful e.g. if you want to change your priorities.

Just some days ago i changed the port of my download client and then i had to change that little information in all of my 11 *arr instances.

**Comment by netty0** [comment] 2021-11-08 04:15
> > Why sync indexers yet "no plans" for download clients? Isn't this the central efficiency prowlarr touts?
> 
> Prowlarr only uses Download Clients to send manual searched results to in Prowlarr. It’s not taking over your download stack, just indexer management.

You can't see the forest for the trees. The fact that Prowlarr would be a good candidate to sync SETTINGS of download clients has nothing to do with how Prowlarr utilizes Download Clients. Users filling out identical fields for Download Clients across Sonarr/Radarr/Prowlarr/etc.. is no different than users filling out indexer settings across Sonarr/Radarr/Prowlarr. Identical cases.

> 
> you also typically only setup and configure a download client once nor replace them often if at all

Says who? This is no different than stating "you typically setup and configure indexer settings once". You're displaying cliche "If I don't need it no one else will" gatekeeper traits.
