### ISSUE TITLE
(Indexer) omgwtfnzbs.me

### ISSUE THREAD

**Issue by jsclayton** [Prowlarr/Prowlarr#167] opened 2021-06-08 16:16 UTC
**Type:** Usenet

**Tracker:** omgwtfnzbs

**URL:** https://omgwtfnzbs.me/

**In Hydra?:** Yes

**Comment by bakerboy448** [comment] 2021-06-08 16:21
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/160

please search prior to creating a GHI

**Closed by bakerboy448** 2021-06-08 16:21 UTC
Labels: Type: Indexer Request

**Comment by jsclayton** [comment] 2021-06-08 16:22
🤦🏼 sorry, filtered by the `Indexer Request` tag, missed that it was only showing open issues.
