### ISSUE TITLE
Separate seed time for episode and season in BroadcastheNet (BTN) indexer options 

### ISSUE THREAD

**Issue by bbK1ngSrb** [Prowlarr/Prowlarr#1248] opened 2022-12-21 12:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

BroadcastheNet has different seed time requrements for eposode and season.
I'd like to have option for BTN in Prownarr indexer setup to split them accordingly. 

![image](https://user-images.githubusercontent.com/64312604/208907908-b00ebdfd-a383-47ee-94b1-75464673c596.png)

### Describe the solution you'd like

Option is already exist if I setup BTN indexer directly in Sonarr, but I'd like to keep all my indexers in Powlarr if possible.

![image](https://user-images.githubusercontent.com/64312604/208908128-7abdd869-bf97-49d9-8c79-bd515c3d46e8.png)

### Describe alternatives you've considered

Using indexer setup in Sonarr or setup same seed time for both seasons and episodes.

### Anything else?

This could be general indexer options settings not only for BTN.

[AB#4522](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4522)

**Comment by bakerboy448** [comment] 2022-12-21 13:10
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/106

**Closed by bakerboy448** 2022-12-21 13:10 UTC
Labels: Type: Feature Request, Status: Needs Triage
