### ISSUE TITLE
[FEAT]: Freeleech support for Torrentleech

### ISSUE THREAD

**Issue by agneevX** [Prowlarr/Prowlarr#504] opened 2021-09-16 13:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Freeleech option for Torrentleech indexer

### Describe the solution you'd like

_Freeleech option for Torrentleech indexer_

### Describe alternatives you've considered

-

### Anything else?

-

[AB#1588](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1588)

**Comment by bakerboy448** [comment] 2021-09-16 13:56
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/317

it exists; turn on advanced settings

please search next time and don't just check the box saying you searched

**Closed by bakerboy448** 2021-09-16 13:56 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by agneevX** [comment] 2021-09-16 14:33
Ok, understood. 

How does one figure out clicking a cog toggles "advanced" settings though?

**Comment by bakerboy448** [comment] 2021-09-17 00:03
It's typically done on the Settings page 
![image](https://user-images.githubusercontent.com/55419169/133703643-f5ea81d2-4a15-4b00-a266-326e34c064fc.png)

the toggle on indexers is really just a matter of convenience
![image](https://user-images.githubusercontent.com/55419169/133703678-0ddfb40d-e503-4520-a419-4224520b95b5.png)
