### ISSUE TITLE
Impossible to grab torrents from Yggtorrent

### ISSUE THREAD

**Issue by JBSDS** [Prowlarr/Prowlarr#721] opened 2021-12-19 23:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, we can't grab trorrents from YggTorrent with Prowlarr for several hours now, all our other tracker work.
We use an identification with cookies.
Do you have an idea to solve this problem?
I attach the recent logs to help.

Thanks for your help

### Expected Behavior

Normally, all our trackers work with prowlarr

### Environment

```markdown
OS: Ubuntu 20.04 LTS
Prowlarr: Prowlarr 0.1.8.1265
Docker Install: Yes
Using Reverse Proxy: yes
Browser: 95.0.2
```

### What branch are you running?

Nightly

### Trace Logs?

https://0bin.net/paste/T31Q5DkE#bK4WnyJNFSDT+vln6r5iJLcShk93hImuBE53ZL0fhmT

[AB#2214](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2214)

**Comment by bakerboy448** [comment] 2021-12-19 23:58
Info logs are not the trace logs required for bug reports


With that said, seems it's not logged in.

have you tried updating the cookie in Prowlarr - seems YGG may have expired them

**Comment by JBSDS** [comment] 2021-12-20 00:00
> Info logs are not the trace logs required for bug reports
> 
> With that said, seems it's not logged in.
> 
> have you tried updating the cookie in Prowlarr - seems YGG may have expired them

Yes, tried to update the cookies but it doesn't work

**Comment by bakerboy448** [comment] 2021-12-20 05:14
that's html spew not the trace logs

seems to be a common issue, how'd you get/upload them?

**Comment by JBSDS** [comment] 2021-12-21 22:34
> that's html spew not the trace logs
> 
> seems to be a common issue, how'd you get/upload them?

ok, now it's good with this link, i don't undurstant why it downloaded this html file.
https://0bin.net/paste/T31Q5DkE#bK4WnyJNFSDT+vln6r5iJLcShk93hImuBE53ZL0fhmT

**Comment by bakerboy448** [comment] 2021-12-21 22:45
Closing; can reopen if needed if this is still an issue

2021-09-15 01:33:31.5|Error|FlareSolverr|Proxy Health Check failed
 
[v0.1.1.875] System.Net.WebException: No route to host (172.20.0.19:8191): 'http://172.20.0.19:8191/v1'

1. you are almost 3 months out of date; upgrade
2. Prowlarr has no route to Flaresolverr
3. you're hitting cloudflare and this the download is blocked

**Comment by bakerboy448** [comment] 2021-12-21 22:46
misread the logs; since the top was 9/2021
re-looking

**Comment by JBSDS** [comment] 2021-12-22 18:41
> 

After all the modifications, it doesn't work :'( . 
Update of the logs : https://0bin.net/paste/vDfqX32+#wHt9Vb4Ak41i6AhY1UzUyuPJTbskhSsM4SkvYytFaRL

**Comment by bakerboy448** [comment] 2021-12-22 18:56
It looks like the grab hit CF then was sent through flareSolverr and came back fine?  there's not error after the grab

It looks like the grab was fine as well?

PS for future logs it'd be helpful if you can just focus / actions on ygg so there is less to go through

<details><summary>Log Snippets</summary>
<p>
```
2021-12-22 19:37:15.2|Trace|Http|Req: 10430 [GET] /24/download?apikey=(removed)&link=L3ZrbStSWW5NWUVQK0dCV1dOdzMwREZsUUpVN1ZYaUJHUVVQL25aOE5POGhySlRVNEdvU2l3K1g2bjNBMzJYaUpWNGVZNXdtZldtWU01bExNd3J2RmhvVkwyaC91TjJxYTNESUpZdWpmREU9&file=Loki.S01E04.MULTI.ENGLISH.DOLBYVISION.2160p.WEB-DL.DDP5.1.HEVC-AXLBEN (from 172.20.10.11)
2021-12-22 19:37:15.2|Trace|RateLimitService|Rate Limit triggered, delaying 'www3.yggtorrent.re' for 0.505 sec
2021-12-22 19:37:15.7|Trace|IndexerHttpClient|Req: [GET] https://nyaa.si/?q=&p=2&f=0&c=1_3&s=id&o=desc
2021-12-22 19:37:15.7|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2021-12-22 19:37:15.7|Debug|Cardigann|Populating config vars
2021-12-22 19:37:15.7|Trace|IndexerHttpClient|Req: [GET] https://www3.yggtorrent.re/engine/download_torrent?id=(removed)
2021-12-22 19:37:15.7|Trace|IndexerHttpClient|Res: [GET] https://www3.yggtorrent.re/engine/download_torrent?id=(removed) 503.ServiceUnavailable
[... CF spew]
2021-12-22 19:37:15.8|Debug|FlareSolverr|Applying FlareSolverr Proxy FlareSolverr to request https://www3.yggtorrent.re/engine/download_torrent?id=(removed)
2021-12-22 19:37:15.8|Trace|HttpClient|Req: [POST] http://172.20.0.19:8191/v1
2021-12-22 19:37:16.1|Trace|IndexerHttpClient|Res: [GET] https://nyaa.si/?q=&p=2&f=0&c=1_3&s=id&o=desc: 200.OK (366 ms)
2021-12-22 19:37:17.6|Trace|HttpClient|Res: [POST] http://172.20.0.19:8191/v1: 200.OK (3849 ms)
[...]
2021-12-22 19:37:19.0|Trace|HttpClient|Req: [GET] https://www3.yggtorrent.re/engine/download_torrent?id=(removed)
2021-12-22 19:37:19.0|Trace|HttpClient|Res: [GET] https://www3.yggtorrent.re/engine/download_torrent?id=(removed) 200.OK (61 ms)
2021-12-22 19:37:19.0|Trace|EventAggregator|Publishing IndexerDownloadEvent
2021-12-22 19:37:19.0|Trace|EventAggregator|IndexerDownloadEvent -> HistoryService
2021-12-22 19:37:19.0|Trace|EventAggregator|IndexerDownloadEvent <- HistoryService
2021-12-22 19:37:19.0|Trace|Http|Res: 10430 [GET] /24/download?apikey=(removed)&link=L3ZrbStSWW5NWUVQK0dCV1dOdzMwREZsUUpVN1ZYaUJHUVVQL25aOE5POGhySlRVNEdvU2l3K1g2bjNBMzJYaUpWNGVZNXdtZldtWU01bExNd3J2RmhvVkwyaC91TjJxYTNESUpZdWpmREU9&file=Loki.S01E04.MULTI.ENGLISH.DOLBYVISION.2160p.WEB-DL.DDP5.1.HEVC-AXLBEN: 200.OK (3841 ms)
```
</p>
</details>

**Comment by JBSDS** [comment] 2022-01-09 17:32
Prowlarr still can't grab on Ygg and we don't understand how to solve the problem. Maybe a reinstallation will solve it ?

**Comment by bakerboy448** [comment] 2022-01-09 17:34
Reinstallation will never fix it.

The issue is not Prowlarr

The issue is YGG is anti automation.

No one else has been reporting issues.

YGG Login I don't believe is working well.

YGG Cookie is working fine - likely your cookie has just expired again.  YGG seems to have also shorted their cookie expire time as well - again anti-automation.

The invalid torrent occurs as you're not logged in.

**Comment by JBSDS** [comment] 2022-01-10 09:51
We already use YGG Cookie witch a recent cookie and it doesn't work, but it work well with Jackett.

**Comment by bakerboy448** [comment] 2022-02-05 23:14
closing; can reopen if/when additional users report the same

**Closed by bakerboy448** 2022-02-05 23:14 UTC
Labels: Type: Bug, Area: Indexers, Area: Cardigann, Status: Waiting for OP

**Comment by terry90** [comment] 2022-03-22 17:43
Same here

**Comment by bakerboy448** [comment] 2022-03-22 18:53
> Same here

This issue has been long closed with workarounds existing.

Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

**Comment by JigSawFr** [comment] 2022-03-22 19:57
Working as expected on my side with cookie version 😃

**Comment by terry90** [comment] 2022-03-23 23:34
Well, the weird thing is testing the indexer is OK (with FlareSolverr) but when I'm trying to grab something I get an error: Invalid torrent file

**Comment by bakerboy448** [comment] 2022-03-23 23:35
Invalid Torrent File happens when your cookie is expired and no longer valid.


Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

**Comment by JigSawFr** [comment] 2022-03-24 23:00
Confirmed that something is not working correctly, prowlarr is not able to always download torrent files
Something to troubleshoot.
