### ISSUE TITLE
Pagination broken

### ISSUE THREAD

**Issue by gituser130** [Prowlarr/Prowlarr#1256] opened 2022-12-25 06:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Clicking the "More" button after searching for a query does not show any more results. I have tried this with 3 indexers - each individually enabled for my test - btdig, tpb and 1337x.to. Looking at System->Events it appears that the URLs being generated are incorrect. Also, the offset to fetch should be computed based on the number of results actually fetched so far, not a fixed static value like 100.

Similar issue when using Radarr to search via indexer added from Prowlarr.

### Expected Behavior

Expected seeing more results fetched  from the indexer.

### Steps To Reproduce

1. Install version 1.0.0.2171
2. Add an indexer (either btdig, tpb or 1337)
3. Go to Search and type a term which would return many results. The term I used for my test was "top"
4. For btdig for example, you will see that only the first 10 search results are returned. Or 60 if using 1337.
5. Click the "More" button.
6. More results are NOT shown.
7. See the logs, you will see that the offset is always 100 instead of 11 or 61 in the cases above. And the URLs being generated are not having the correct page in the query string.

### Environment

```markdown
- OS: Windows
- Prowlarr: 1.0.0.2171
- Docker Install: NA
- Using Reverse Proxy: NA
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

2022-12-24 22:09:48.0|Info|ReleaseSearchService|Searching indexer(s): [1337x] for Term: [top], Offset: 0, Limit: 100, Categories: []
2022-12-24 22:09:48.0|Info|Cardigann|Adding request: https://1337x.to/sort-search/top/size/desc/1/
2022-12-24 22:09:49.9|Info|Cardigann|Adding request: https://1337x.to/sort-search/top/size/desc/2/
2022-12-24 22:09:51.8|Info|Cardigann|Adding request: https://1337x.to/sort-search/top/size/desc/3/
2022-12-24 22:09:56.8|Info|ReleaseSearchService|Searching indexer(s): [1337x] for Term: [top], Offset: 100, Limit: 100, Categories: []
2022-12-24 22:09:56.8|Info|Cardigann|Adding request: https://1337x.to/sort-search/top/size/desc/1/
2022-12-24 22:09:58.5|Info|Cardigann|Adding request: https://1337x.to/sort-search/top/size/desc/2/
2022-12-24 22:10:00.4|Info|Cardigann|Adding request: https://1337x.to/sort-search/top/size/desc/3/

[AB#4545](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4545)

**Comment by Qstick** [comment] 2022-12-25 06:26
The three you are trying don't support pagination. Mostly it's newznab/usenet Indexers that do currently.

**Comment by gituser130** [comment] 2022-12-25 07:10
Then prowlarr should add support for it in the indexers since the 1337 and btdig websites both support pagination. I suspect this should be a very common usecase given that these are populator public sources.

Any idea on ETA when prowlarr can add pagination support for these and similar sources?

If you can give me some code pointers I can try to add it.

**Comment by bakerboy448** [comment] 2022-12-25 15:01
Duplicate of #379 (renamed to be broader)

**Closed by bakerboy448** 2022-12-25 15:01 UTC
Labels: Type: Bug, Type: Duplicate

**Comment by bakerboy448** [comment] 2023-02-27 01:31
bandaided https://github.com/Prowlarr/Prowlarr/commit/24f6c937da5670ae37d7683f986807b442a71f19
