### ISSUE TITLE
Support for categories 10000 and over

### ISSUE THREAD

**Issue by keldian** [Prowlarr/Prowlarr#883] opened 2022-03-09 15:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Many torrent trackers have TV/movie categories in the 10000s:
![image](https://user-images.githubusercontent.com/953679/157473947-bbf21b62-cef8-49f8-90e6-43466909fed6.png)

To Prowlarr, these are not considered. The list cuts off at 8020 in `Settings -> Edit Application -> Sync Categories`:
![image](https://user-images.githubusercontent.com/953679/157474473-6b4cdfce-18da-493a-b995-0754949712b0.png)

Maybe I'm missing something and these categories still get monitored and searched by Radarr & Sonarr despite not being selected in the indexer settings, but I have not noticed any evidence to confirm that.

### Describe the solution you'd like

I'd like to see categories 10000-10100 selectable (without necessarily being labelled), resulting in their selection state being carried over to the PVR indexer settings.

### Describe alternatives you've considered

Select them manually in the Radarr & Sonarr indexer settings? That can get tedious when you have 20+ indexers, plus they eventually get reset by Prowlarr app indexer sync.

### Anything else?

¯\_(°_o)_/¯

[AB#2782](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2782)

**Comment by bakerboy448** [comment] 2022-03-09 15:58
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/722

they're mapped to their standardized categories

**Closed by bakerboy448** 2022-03-09 15:58 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by keldian** [comment] 2022-03-09 16:22
Irrelevant. There is no category in `Sync Categories` that I can select, which will result in 10000+ categories being selected in PVR indexer settings. Even when I select ALL available categories and trigger `Sync App Indexers`, 10000s will remain empty in the PVR indexer settings.
