### ISSUE TITLE
[FEAT]: Sync Download Clients Settings to Apps - Central Managment Improvement

### ISSUE THREAD

**Issue by neo-neo1** [Prowlarr/Prowlarr#583] opened 2021-11-06 04:41 UTC
**Feature Request:** Just like Prowlarr syncs indexers to Sonarr/Radarr/etc.. the `Download Clients` settings in Prowlarr could be included in syncs. An improvement of central management efficiency for *arr apps that Prowlarr touts.

Users configure identical settings for `Download Clients` in Prowlarr, Radarr, Sonarr, and etc... Why not sync this setting just like indexers?

**Comment by bakerboy448** [comment] 2021-11-06 04:58
Please don't butcher the template and please actually search

Duplicate of https://github.com/Prowlarr/Prowlarr/issues/509

Duplicate of https://github.com/Prowlarr/Prowlarr/issues/323

**Closed by bakerboy448** 2021-11-06 04:58 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by neo-neo1** [comment] 2021-11-06 05:03
> Please don't butcher the template and please actually search
> 
> Duplicate of #509
> 
> Duplicate of #323

My dear bureaucrat, 
I'll continue "butchering" redundant templates as long as you blanket require `issue` templates for suggestions.
You have me on the duplicate, though.

Thanks,
A human who doesn't prefer badly fitting templates.
