### ISSUE TITLE
Cannot add torrent indexer

### ISSUE THREAD

**Issue by Serph91P** [Prowlarr/Prowlarr#1011] opened 2022-05-19 05:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I cannot add speed torrent reloaded, in Jackett it works just fine. Error message: 
`Unable to connect to indexer: Login failed: No form found on https://st-tracker.eu/sessioncheck.php?session=1 using form selector form`

### Expected Behavior

Can add this torrent indexer since it's working in Jackett 

### Steps To Reproduce

try to add speed torrent reloaded.

### Environment

```markdown
- OS: unRAID
- Prowlarr:0.3.0.1730
- Docker Install:yes
- Using Reverse Proxy:no
- Browser:chrome
```

### What branch are you running?

Master

### Trace Logs?

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/8725106/prowlarr.trace.txt)

[AB#3166](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3166)

**Comment by bakerboy448** [comment] 2022-05-19 05:11
Duplicate of #526

**Comment by bakerboy448** [comment] 2022-05-19 05:11
Please search next time

**Closed by bakerboy448** 2022-05-19 05:11 UTC
Labels: Type: Bug, Status: Needs Triage
