### ISSUE TITLE
Use proxy for FlareSolver requests

### ISSUE THREAD

**Issue by akrigator** [Prowlarr/Prowlarr#1910] opened 2023-10-31 18:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I'm using Tor addon as proxy for lidarr, sonarr, radarr and prowlarr addons to bypass censorship restrictions. Those addons works great via tor proxy, except one scenario for prowlarr. Some indexers have cloudflare protection, which could not be resolved since Cloudflare is also blocked. I got error when I'm adding the FlareSolverr proxy into prowlarr:

```
2023-10-27 00:06:56 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}}
2023-10-27 00:07:00 INFO     127.0.0.1 GET http://127.0.0.1:8191/ 200 OK
2023-10-27 00:07:05 INFO     127.0.0.1 GET http://127.0.0.1:8191/ 200 OK
2023-10-27 00:07:10 INFO     127.0.0.1 GET http://127.0.0.1:8191/ 200 OK
2023-10-27 00:07:11 ERROR    Error: Error solving the challenge. Cloudflare has blocked this request. Probably your IP is banned for this site, check in your web browser.
2023-10-27 00:07:11 INFO     Response in 14.584 s
2023-10-27 00:07:11 INFO     172.30.32.1 POST http://192.168.88.13:8191/v1 500 Internal Server Error
```

I guess that it also may be workarounded by setup a tor proxy in FlareSolverr addon.

### Describe the solution you'd like

Have an ability to configure a proxy for FlareResoler at adding subwindow:
![image](https://github.com/Prowlarr/Prowlarr/assets/695335/4eb489fb-3f9a-42bc-b0cf-cb63b5978133)

and than use this value as `proxy` parameter for [create](https://github.com/FlareSolverr/FlareSolverr#-sessionscreate) and [get](https://github.com/FlareSolverr/FlareSolverr#-requestget) requests

### Describe alternatives you've considered

N/A

### Anything else?

Use tagging approach to reuse already available proxies

**Comment by bakerboy448** [comment] 2023-10-31 18:27
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/1686

**Closed by bakerboy448** 2023-10-31 18:27 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by akrigator** [comment] 2023-10-31 19:00
@bakerboy448, could you please clarify how to setup FlareSolver proxy to use another for requests? Since i don't see such way in #1686?

**Comment by akrigator** [comment] 2023-10-31 19:03
Oh, it uses general 
![image](https://github.com/Prowlarr/Prowlarr/assets/695335/5b15c5f0-17e4-4d45-8dd5-77cf35e9ec66)
shame on me

**Comment by akrigator** [comment] 2023-10-31 21:25
@bakerboy448, could it be configured per Flare Resolver proxy only instead of systemwide? I guess in my case i need only for one

**Comment by pmialon** [comment] 2023-12-12 12:28
@bakerboy448 The defined setup didn't work for me, when I define a Proxy in General the flaresolverr received the following request:
`{'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://example.com', 'proxy': {'url': 'socks5://socksproxy:9050/'}}`
or
`{'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://example.com', 'proxy': {'url': 'http://httpproxy:8080/'}}`

The issue is the trailing / at the end of the proxy.url: flaresolverr failed with ERR_NO_SUPPORTED_PROXIES

**Comment by bakerboy448** [comment] 2023-12-12 13:56
@pmialon thats an issue you'll need to take up with Flaresolverr not supporting a proxy parameter as a valid URI
