### ISSUE TITLE
manual grab from prowlarr notifiarr notification 

### ISSUE THREAD

**Issue by reitenth** [Prowlarr/Prowlarr#1399] opened 2023-02-05 20:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

.

### Describe the solution you'd like

when i manually grab a release from prowlarr, i would like to get notifiarr integration like it does with sonarr/radarr.

### Describe alternatives you've considered

.

### Anything else?

.

[AB#4864](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4864)

**Comment by bakerboy448** [comment] 2023-02-08 16:28
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/958

**Closed by bakerboy448** 2023-02-08 16:28 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by reitenth** [comment] 2023-02-08 16:49
lol i was told to post this here as it is getting added according to devs in notifiarr discord

**Comment by Qstick** [comment] 2023-02-19 17:27
This was correctly marked as a duplicate issue of #958, PR is up for this at #1448
