### ISSUE TITLE
YGGtorrent indexer changed their URL

### ISSUE THREAD

**Issue by Nindohana** [Prowlarr/Prowlarr#954] opened 2022-04-14 04:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The YGGtorrent french indexer changed their URL, it's now yggtorrent.la instead of .re

### Expected Behavior

Change the proposed URL from yggtorrent.re to yggtorrent.la
Also, is it possible in the future to be able to manually change an indexer URL ?

Thank you.

### Environment

```markdown
- OS: 
- Prowlarr: 0.2.0.1678
- Docker Install: YES
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Develop

### Trace Logs?

Not needed.

[AB#2990](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2990)

**Comment by bakerboy448** [comment] 2022-04-14 04:29
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/948

please search next time

**Closed by bakerboy448** 2022-04-14 04:29 UTC
Labels: Type: Bug, Status: Needs Triage
