### ISSUE TITLE
[BUG]: Cannot modify indexer which responds with an error

### ISSUE THREAD

**Issue by carbolymer** [Prowlarr/Prowlarr#572] opened 2021-11-01 15:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. Edit indexer which is returning an error
2. Try to save indexer (e.g. after changing priority, or api limit)
3. Indexer endpoint error prevents user from saving of the indexer.

### Expected Behavior

1. Edit indexer which is returning an error
2. Try to save indexer (e.g. after changing priority, or api limit)
3. Indexer is saved despite indexer endpoint returning an error.

This is particularly useful when indexer is temporarily down, and the user wants to lower it's priority, or change api limits.

### Steps To Reproduce

see above

### Environment

```markdown
- OS: Archlinux
- Prowlarr: 0.1.1.1030
- Docker Install: no
- Using Reverse Proxy: no
- Browser: n/a
```

### What branch are you running?

Master

### Anything else?

no

[AB#1840](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1840)

**Comment by bakerboy448** [comment] 2021-11-01 15:32
Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

duplicate of https://github.com/Prowlarr/Prowlarr/issues/226

you should be able to force save it OR disable it force save it and re-enable as needed
https://github.com/Prowlarr/Prowlarr/issues/461#issuecomment-916987862

**Closed by bakerboy448** 2021-11-01 15:32 UTC
Labels: Type: Bug, Status: Needs Triage

**Comment by carbolymer** [comment] 2021-11-01 15:36
Thanks. The force save isn't that obvious from UI.
