### ISSUE TITLE
[BUG]: BTDigg not synced to Sonarr/Radarr

### ISSUE THREAD

**Issue by Jorman** [Prowlarr/Prowlarr#393] opened 2021-08-04 21:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can add BTDigg inside Prowlarr but seems that is not automatically synced with Radarr/Sonarr

### Expected Behavior

Have the indexer automatically synced

### Environment

```markdown
- OS: Debian 10
- Prowlarr: 0.1.0.608-ls10 by linuxserver.io
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: Chrome
```

### What branch are you running?

Develop

### Anything else?

Nothing

[AB#1384](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1384)

**Comment by bakerboy448** [comment] 2021-08-04 21:39
1 - what categories are listed for that indexer on the indexer page?
2 - need trace logs of a triggered sync for radarr/sonarr with this indexer not being synced
https://wiki.servarr.com/prowlarr/troubleshooting#logging-and-log-files

**Comment by Jorman** [comment] 2021-08-04 21:57
Hi,
1. 8000 - Other
2. Yes, other indexers works, I not checked all because I'm switching but for now yes
3. Full Sync in both
4. Yes, I made a screen see after
5. Logs grabbed

prowlarr.debug
https://hastebin.com/aqifohijuz.apache
and prowlarr.trace
https://hastebin.com/qexagicuzo.yaml

The funny thing is that if I look at the logs, it looks like BTDigg doesn't exist, but
![image](https://user-images.githubusercontent.com/5203988/128260024-ebb771fb-5386-4be4-88dc-3a877ac72e11.png)

Any idea?

**Comment by bakerboy448** [comment] 2021-08-04 22:04
Yup see my edit on my comment.  I would not expect BtDigg to ever be synced to radarr/sonarr/ or any app for that matter because it is a crap indexer that does not have any categories.

Work around:  Add it manually to the apps as a Torznab - you can get the indexer's id from the little info icon to the right. 

Prowlarr is otherwise working as designed and intended, so likely will close this after some internal discussions on if we wish to have some sort of way to force sync non-compatible indexers.  Due to the likely support nightmare, I'd foresee that as unlikely.

also it looks like you have a ton of indexers added...that is actually not advised and causes issues with radarr/sonarr due to paging limits, quantity of results returned, etc.  You do not need to add every single public indexer nor should you ever - frankly it's stupid and illogical  given most public trackers scrape each other as well. Anything more than 10-15 indexers or so and you're likely shooting off your foot for no reason.   Less is more.

**Comment by Jorman** [comment] 2021-08-04 22:12
Ok just saw your edit! Ok, so all only "Others" this will not ever synced with Radarr/Sonarr? Are all indexers that have a miscellaneous category "bad"? I see and understand what you said, let's see what they say

Yes you are right, not knowing all the indexers, I still do not know well which ones generate more results, I'm trying to see the indexers that generate more grabs to "select" the best, but any advice is welcome

**Comment by bakerboy448** [comment] 2021-08-04 22:55
Closing in lieu of https://github.com/Prowlarr/Prowlarr/issues/394

**Closed by bakerboy448** 2021-08-04 22:55 UTC
Labels: Status: Needs Triage
