### ISSUE TITLE
[FEAT]: Filter down "Apps" by "Protocol"

### ISSUE THREAD

**Issue by the-lazy-fox** [Prowlarr/Prowlarr#411] opened 2021-08-10 21:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I'm currently using mainly Jackett and torrenting for my PVR needs like Jackett/Radarr/Sonarr/...
On the side, I'm using Usenet for more manual deep searches.

The issue I have, is that I can't enter all my torrents and usenets indexers in Prowlarr + Sync with Sonarr and Radarr as they will ALL flow with the sync (and I would like to have it)

### Describe the solution you'd like

It would be great if like "Tags" we could chose Usenet /  torrent or both in a protocol filter

### Describe alternatives you've considered

I'm considered making a Tag Torrent and a tag Usenet but it's a non sense honestly has the protocol is already a well manage field.

### Anything else?

Thank you for this project and going back to testing 👍🏼

**Comment by bakerboy448** [comment] 2021-08-10 21:06
Duplicate of #90

**Closed by bakerboy448** 2021-08-10 21:06 UTC
Labels: Type: Feature Request, Status: Needs Triage
