### ISSUE TITLE
Requesting option to disable appending (Prowlarr) to synced indexers.

### ISSUE THREAD

**Issue by devanteweary** [Prowlarr/Prowlarr#2264] opened 2024-10-21 14:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No problem.

### Describe the solution you'd like

Currently, when Prowlarr syncs to Radarr/Sonarr/Lidarr etc. it appends `(Prowlarr)` to the name of the indexer. 
At least for me on a 1080p screen, this results in every single search result in the *arrs being two lines.

For instance, if I do an interactive search, the results will always be double space because of the extra space caused by the `(Prowlarr)` in the indexer column.

I'm sure many of us use Prowlarr exclusively to add indexers, so no need to distinguish between which ones are added by Prowlarr.

### Describe alternatives you've considered

Manually renaming the indexers in the *arrs. 
It just reverts the name when Prowlarr syncs again.

I've also tried going to `Prowlarr > Settings > Apps` and changing the connections there to Add/Remove only.  
This kept my manual name changes in the *arr apps themselves but also makes it so any changes I make to an indexer doesn't get synced. For instance, if I change priority in Prowlarr, it doesn't sync to the *arrs.

Oh I don't think there's a way to resize columns in the *arrs.

### Anything else?

This is a search in Sonarr. Only one of these results is naturally a 2-liner due to the title. 
The rest are two lines due to (Prowlarr) being added.

![image](https://github.com/user-attachments/assets/1e19117f-b512-41a6-a40d-dc9db85985f5)

(I swear I searched if this has been asked before, just couldn't find another request like this!)

**Comment by bakerboy448** [comment] 2024-10-21 14:57
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/544

**Closed by bakerboy448** 2024-10-21 14:57 UTC
Labels: Type: Feature Request, Status: Needs Triage
