### ISSUE TITLE
[BUG]: Flaresolverr breaks torrent download on YggTorrent

### ISSUE THREAD

**Issue by RomLecat** [Prowlarr/Prowlarr#478] opened 2021-08-31 13:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When downloading a torrent release in YggTorrent after a search in Prowlarr (or any API call made to Prowlarr), the download never happens (regardless if it's a download of torrent file or direct send to download client).

### Expected Behavior

Downloading a torrent with FlareSolverr enabled should work.

### Steps To Reproduce

Configure YggTorrent with valid credentials, and configure a FlareSolverr proxy on Prowlarr.

### Environment

```markdown
- OS: Rocky Linux 8
- Prowlarr: v0.1.1.875
- Docker Install: N/A
- Using Reverse Proxy: Caddy
- Browser: Chrome
```

### What branch are you running?

Develop

### Anything else?

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/7085534/prowlarr.trace.txt)

[AB#1541](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1541)

**Comment by RomLecat** [comment] 2021-08-31 16:52
By the way, please redact credentials from logs. This is very dangerous to keep them in here.

**Comment by bakerboy448** [comment] 2021-08-31 17:06
> By the way, please redact trackers credentials from logs. This is very dangerous to keep them in here.

Added to the existing issue.

https://github.com/Prowlarr/Prowlarr/issues/280#issuecomment-909421776

there's issues with the cleanse not scrubbing the post or response

**Comment by bakerboy448** [comment] 2021-08-31 23:04
Log cleanse fixed in this PR: https://github.com/Prowlarr/Prowlarr/pull/479

**Comment by bakerboy448** [comment] 2021-09-01 01:31
Can't reproduce this locally on my development instance and logs did not seem to indicate any error?

1. Setup YGG (non-cookie)
2. Setup Flaresolverr in Prowlarr and ensure assigned for YGG
3. Search for any random thing in Prowlarr
4. Send to torrent client
5. Release shows in client and client begins downloading.

**Comment by RomLecat** [comment] 2021-09-01 06:13
I'm not really sure why you don't have it. @alphachoups also reported to have this error (he's the one who noticed it, actually) and I can't get any torrent to work.

I think the issue is due to the output of FlareSolverr:
```
2021-09-01 08:10:57.7|Debug|Api|[POST] /api/v1/search: 200.OK (18 ms)
2021-09-01 08:10:58.9|Trace|IndexerHttpClient|Res: [POST] https://flaresolverr.internal.home.lecat.network/v1: 200.OK (1178 ms)
2021-09-01 08:10:59.4|Trace|IndexerHttpClient|Res: [POST] https://flaresolverr.internal.home.lecat.network/v1: 200.OK (3090 ms)
2021-09-01 08:10:59.4|Error|GlobalExceptionHandlers|Task Error

[v0.1.1.875] MonoTorrent.TorrentException: Invalid torrent file specified
 ---> MonoTorrent.BEncoding.BEncodingException: Invalid data found. Aborting
   at MonoTorrent.BEncoding.BEncodeDecoder.DecodeTorrent(RawReader reader)
   at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(RawReader reader)
   at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(Stream s)
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   --- End of inner exception stack trace ---
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   at MonoTorrent.Torrent.Load(Byte[] data)
   at NzbDrone.Core.Download.TorrentFileInfoReader.GetHashFromTorrentFile(Byte[] fileContents) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentFileInfoReader.cs:line 14
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(ReleaseInfo release, IIndexer indexer, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 144
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(ReleaseInfo release, Boolean redirect, IIndexer indexer) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 116
   at NzbDrone.Core.Download.DownloadService.SendReportToClient(ReleaseInfo release, String source, String host, Boolean redirect) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 77
```

But unfortunately FlareSolverr responses does not appear to be logged, so it's hard to tell.

**Comment by bakerboy448** [comment] 2021-09-01 21:34
Well like I said I cannot reproduce it with flaresolverr v1.2.9 and the code for prowlarr 0.1.1.913

Possible ideas that come to mind:
- Host PC regional differences
- bad torrent file
- random fix between .875 and .913

I'd suggest working on checking flaresolverr first, I assume they have a method to increase logging to assist in troubleshooting.

Does the issue occur without flaresolverr?

**Comment by RomLecat** [comment] 2021-09-01 21:41
No, the issue does not happen without FlareSolverr. The issue is also not happening with Jackett (same host).

FlareSolverr does not report any error (most verbose mode does not log responses unfortunately):
```
Sep 01 23:38:06 flaresolverr flaresolverr[715349]: 2021-09-01T23:38:06+02:00 INFO REQ-7 Incoming request: POST /v1
Sep 01 23:38:06 flaresolverr flaresolverr[715349]: 2021-09-01T23:38:06+02:00 INFO REQ-7 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www3.yggtorrent.nz/engine/download_torrent?id=796617","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"}
Sep 01 23:38:06 flaresolverr flaresolverr[715349]: 2021-09-01T23:38:06+02:00 DEBUG REQ-7 Launching browser...
Sep 01 23:38:07 flaresolverr flaresolverr[715349]: 2021-09-01T23:38:07+02:00 DEBUG REQ-7 Using custom UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Sep 01 23:38:07 flaresolverr flaresolverr[715349]: 2021-09-01T23:38:07+02:00 DEBUG REQ-7 Adding custom headers: {}
Sep 01 23:38:07 flaresolverr flaresolverr[715349]: 2021-09-01T23:38:07+02:00 DEBUG REQ-7 Navigating to... https://www3.yggtorrent.nz/engine/download_torrent?id=796617
Sep 01 23:38:07 flaresolverr flaresolverr[715349]: 2021-09-01T23:38:07+02:00 DEBUG REQ-7 Overrides: {"headers":{"upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"}}
Sep 01 23:38:07 flaresolverr flaresolverr[715349]: 2021-09-01T23:38:07+02:00 INFO REQ-7 Cloudflare detected
Sep 01 23:38:07 flaresolverr flaresolverr[715349]: 2021-09-01T23:38:07+02:00 DEBUG REQ-7 Javascript challenge not detected. Status code: 200
Sep 01 23:38:07 flaresolverr flaresolverr[715349]: 2021-09-01T23:38:07+02:00 INFO REQ-7 Challenge solved.
Sep 01 23:38:07 flaresolverr flaresolverr[715349]: 2021-09-01T23:38:07+02:00 INFO REQ-7 Response in 1.017 s
```

Interestingly enough, when clicking a download link on Prowlarr, it instantly shows the download icon without any loading, while any "real" test/browsing/downloading from working tracker takes several seconds (as expected).

**Comment by Alphachoups** [comment] 2021-09-01 21:57
> I'm not really sure why you don't have it. @Alphachoups also reported to have this error (he's the one who noticed it, actually) and I can't get any torrent to work.

Seams that there's a confusion. I have reported in another post a problem with a timeout login in Jackett that make the Yggtorrent tracker as in failure. This problem continue to appear without FlareSolverr (And yes I'm 100% sure).

Here the problem is that Flaresolverr or something else corrupt the torrent file. I'm not concerned by this problem and I never encounter it myself so it's totally possible that Flaresolverr is responsible of that (I dont use it anymore).

**Comment by RomLecat** [comment] 2021-09-01 22:18
Actually, after a lot of enabling/disable FlareSolverr, it now works again for some reason. Honestly don't know why it's working now...

Anyway, closing this ticket. Thanks for the help!

**Comment by almottier** [comment] 2021-09-01 22:30
I  still have the issue  with or without flaresolverr enabled

```
[v0.1.1.875] MonoTorrent.TorrentException: Invalid torrent file specified
 ---> MonoTorrent.BEncoding.BEncodingException: Invalid data found. Aborting
   at MonoTorrent.BEncoding.BEncodeDecoder.DecodeTorrent(RawReader reader)
   at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(RawReader reader)
   at MonoTorrent.BEncoding.BEncodedDictionary.DecodeTorrent(Stream s)
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   --- End of inner exception stack trace ---
   at MonoTorrent.Torrent.Load(Stream stream, String path)
   at MonoTorrent.Torrent.Load(Byte[] data)
   at NzbDrone.Core.Download.TorrentFileInfoReader.GetHashFromTorrentFile(Byte[] fileContents) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentFileInfoReader.cs:line 14
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(ReleaseInfo release, IIndexer indexer, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 144
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(ReleaseInfo release, Boolean redirect, IIndexer indexer) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 116
   at NzbDrone.Core.Download.DownloadService.SendReportToClient(ReleaseInfo release, String source, String host, Boolean redirect) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 77
   ```

**Comment by bakerboy448** [comment] 2021-09-01 22:49
and if you open the torrent file up in a text editor what does it look like?

either way it doesn't appear this is exactly a prowlarr issue if the site is providing invalid torrents (which it seems to be)

**Comment by almottier** [comment] 2021-09-01 22:53
hum this is HTML...
```
$ cat Adieu\ Les\ Cons\ 2020\ CUSTOM\ FRENCH\ WEB-DL\ 1080p\ EAC3\ x264-Naf185\ \(Bye\ Bye\ Morons\)\ \(1\).torrent
<html><head></head><body>Vous devez vous connecter pour télécharger un torrent</body></html>%
```

**Comment by truenicoco** [comment] 2021-09-15 11:11
I think this issue should be reopened.

I am hitting the same bug fir a few days (it was working just fine before), all downloaded torrents from YGG have the same content (@almottier cat'ed it just above). I tried upgrading flaresolverr to the latest version, but it does not seem to help.

Prowlarr is great so I would be happy to help debug that, let me know if I can.

**Comment by RomLecat** [comment] 2021-09-15 11:11
Same here. As before, disabling FlareSolverr resolves the issue.

**Comment by almottier** [comment] 2021-09-15 21:03
Could you reopen this issue @RomLecat or @bakerboy448  🙏  ?

**Comment by piitaya** [comment] 2021-09-27 22:02
I have the issue too (Prowlarr 0.1.1.953, Flaresolverr 1.2.9)
 
## Step to reproduce
1. Create YggTorrent indexer with cloudflare tag
2. Create Flaresolverr indexer with cloudflare tag
3. Create Blackhole download client
4. Go to "search" page
5. Search for a torrent
6. Click on "Add release to download client"
7. The torrent is not downloaded into the blackhole (you can see in trace)

## Trace
```
2021-09-27 23:42:01.4|Trace|Http|Res: 39 [GET] /prowlarr/api/v1/search?query=dune&indexerIds=1: 200.OK (31087 ms)
2021-09-27 23:42:10.1|Trace|Http|Req: 40 [POST] /prowlarr/api/v1/search (from 82.*.*.161)
2021-09-27 23:42:10.1|Debug|FlareSolverr|Applying FlareSolverr Proxy FlareSolverr to request https://www3.yggtorrent.nz/engine/download_torrent?id=(removed)
2021-09-27 23:42:10.1|Trace|IndexerHttpClient|Req: [POST] http://flaresolverr:8191/v1
2021-09-27 23:42:10.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-09-27 23:42:10.1|Trace|Http|Res: 40 [POST] /prowlarr/api/v1/search: 200.OK (77 ms)
2021-09-27 23:42:12.3|Trace|IndexerHttpClient|Res: [POST] http://flaresolverr:8191/v1: 200.OK (2188 ms)
2021-09-27 23:42:12.3|Debug|TorrentBlackhole|Torrent download failed, trying magnet. (Invalid torrent file specified)
```

**Comment by Mrmel94** [comment] 2021-10-05 09:48
Same poblem here, invalid torrent file in logs with prowlarr, flaresolverr and yggtorrent's indexer. 
Everything works fine if I disable flaresolverr.
Same torrent works fine with flaresolverr and Jackett

**Comment by jncanches** [comment] 2021-11-14 13:48
Exactly the same here.
Too bad :( Prowlarr is way better than Jackett !

**Comment by Qstick** [comment] 2021-11-14 23:02
> Exactly the same here.
> Too bad :( Prowlarr is way better than Jackett !

It's on the short list to fix before next version release

**Closed** 2021-11-19 03:48 UTC
Labels: Type: Bug
