### ISSUE TITLE
Add the ability to set indexer priorities per configured App.

### ISSUE THREAD

**Issue by Tuuune** [Prowlarr/Prowlarr#337] opened 2021-07-11 12:06 UTC
**Is your feature request related to a problem? Please describe.**
It is possible to set an indexer priority currently,  but the same priority is applied to all *arr instances for that indexer. I would like to set an indexer priority per *arr service, as some indexers may be better for movies, but not as good for tv shows, same goes vice versa. Of course these are just examples and the same would apply to music, books etc.

**Describe the solution you'd like**
Add values for indexer priorities to indexers->Edit Indexer for every service that you have configured in Settings ->Apps

**Describe alternatives you've considered**
I have not found another way or workaround to achieve what i want to do in Prowlarr, one could adjust the indexer priorities in each *arr service independently, but that would defeat the purpose of Prowlarr being the one place to configure everything.

**Additional context**
NA

[AB#1250](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1250)

**Comment by bakerboy448** [comment] 2021-07-11 12:07
Duplicate of several... please search prior to opening new GHI

**Closed by bakerboy448** 2021-07-11 12:07 UTC
Labels: Type: Feature Request
