### ISSUE TITLE
[SecretCinema] Issue with HTML decoding titles

### ISSUE THREAD

**Issue by mynameisbogdan** [Prowlarr/Prowlarr#1238] opened 2022-12-15 19:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Seems to be an issue with `HtmlDecode` when using SC.

![Screenshot 2022-12-15 at 20 58 10](https://user-images.githubusercontent.com/707714/207944561-f1c038a7-98ec-4230-9eb4-7f89e73c9116.jpg)

### Expected Behavior

Like others:
![Screenshot 2022-12-15 at 20 57 54](https://user-images.githubusercontent.com/707714/207944588-15b3807a-3604-4a80-bc8c-ff79b8c676d4.jpg)

### Steps To Reproduce

`t=movie&imdbId=tt0045152`

### Environment

```markdown
- OS: Unraid
- Prowlarr: 0.4.10.2111
- Docker Install: Y
```

### What branch are you running?

Develop

### Trace Logs?

N/A

[AB#4472](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4472)

**Comment by bakerboy448** [comment] 2022-12-15 19:12
logs are not optional.....need the indexer response from the site to see what they're sending

its using dotnet's native htmldecode function which handles html characters fine.

**Comment by mynameisbogdan** [comment] 2022-12-15 19:49
The trace logs don't contain the indexer response.

```
2022-12-15 21:33:01.3|Info|ReleaseSearchService|Searching indexer(s): [SecretCinema] for Term: [] | ID(s): IMDbId:[0045152], Offset: 0, Limit: 0, Categories: []
2022-12-15 21:33:01.3|Debug|SecretCinema|Downloading Feed https://secret-cinema.pw/ajax.php?action=browse&order_by=time&order_way=desc&cataloguenumber=tt0045152
2022-12-15 21:33:01.3|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2022-12-15 21:33:01.3|Trace|IndexerHttpClient|Req: [GET] https://secret-cinema.pw/ajax.php?action=browse&order_by=time&order_way=desc&cataloguenumber=tt0045152
2022-12-15 21:33:01.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2022-12-15 21:33:01.4|Trace|Scheduler|Pending Tasks: 0
2022-12-15 21:33:01.4|Trace|IndexerHttpClient|Res: [GET] https://secret-cinema.pw/ajax.php?action=browse&order_by=time&order_way=desc&cataloguenumber=tt0045152: 200.OK (2092 bytes) (52 ms)
2022-12-15 21:33:01.4|Trace|EventAggregator|Publishing IndexerQueryEvent
2022-12-15 21:33:01.4|Trace|EventAggregator|IndexerQueryEvent -> HistoryService
2022-12-15 21:33:01.4|Trace|EventAggregator|IndexerQueryEvent <- HistoryService
2022-12-15 21:33:01.4|Trace|EventAggregator|IndexerQueryEvent ~> ReleaseAnalyticsService
2022-12-15 21:33:01.4|Trace|EventAggregator|IndexerQueryEvent <~ ReleaseAnalyticsService
2022-12-15 21:33:01.4|Debug|ReleaseSearchService|Total of 3 reports were found for Term: [] | ID(s): IMDbId:[0045152], Offset: 0, Limit: 0, Categories: [] from 1 indexer(s)
```

Sample from the response:
```json
        "groupId": 2497,
        "groupName": "Singin&#39; in the Rain",
        "artist": "Gene Kelly & Stanley Donen",
```

The only weird thing seems to be a double HTML decoding here:
https://github.com/Prowlarr/Prowlarr/blob/95a2bd3d03a2c66563e31c243e4e54dff2e5be1a/src/NzbDrone.Core/Indexers/Definitions/SecretCinema.cs#L117-L122

> its using dotnet's native htmldecode function which handles html characters fine.

Also from a quick google search there are 2 decode functions, `HttpUtility.HtmlEncode` and `WebUtility.HtmlEncode`, which don't behave the same.

**Comment by bakerboy448** [comment] 2022-12-15 20:03
![image](https://user-images.githubusercontent.com/55419169/207955022-e994ec65-3d8c-4282-b582-d84c1333e390.png)
for future reference

sample response works, thanks!

> double HTML decoding

which _should_ be a non-issue.

as far as httputility vs webutility - So they all, ultimately, use System.Net.WebUtility.HtmlEncode.
from a [SO post ](https://stackoverflow.com/questions/40678598/differences-between-different-net-framework-htmlencode-methods)where someone dug through the dotnet source

**Comment by mynameisbogdan** [comment] 2022-12-15 20:22
> for future reference

Okay, thank you.

> which _should_ be a non-issue.

true, but I'm not familiar with C# 🤷‍♂️


> as far as httputility vs webutility - So they all, ultimately, use System.Net.WebUtility.HtmlEncode.
> from a [SO post ](https://stackoverflow.com/questions/40678598/differences-between-different-net-framework-htmlencode-methods)where someone dug through the dotnet source

I understand, so there's no way to resolve this is what you're saying?

**Comment by bakerboy448** [comment] 2022-12-15 20:36
> so there's no way to resolve this is what you're saying?

would need to play with it and see what the issue is - on it's face....nothing stands out for why it would not be working / should be decoding that

**Comment by mynameisbogdan** [comment] 2022-12-15 20:40
Okay, thank you.

**Comment by Qstick** [comment] 2022-12-20 21:21
Pushed a fix for the double decode, though I'm not sure that was the underlying problem to what's being reported. If you can test that would be great, otherwise I may need an invite or a sample response.

**Comment by mynameisbogdan** [comment] 2022-12-20 22:01
@Qstick - I just tested nightly with these changes and sadly it doesn't fix the issue. [Here's a sample response](https://privatebin.net/?23acd0f2dcd33896#BrERvMhzZp6sKUnFg32NzpNWbSLExYpVFssk1LZeeXxH).

**Comment by Qstick** [comment] 2022-12-20 22:05
Thanks, let me have a go with this info.

**Comment by Qstick** [comment] 2022-12-20 22:24
Should be good now. Thanks Again!

**Closed** 2022-12-20 22:24 UTC
Labels: Type: Bug, Status: Needs Triage, Area: Indexer

**Comment by mynameisbogdan** [comment] 2022-12-20 22:26
@Qstick - btw my bad, it seems like the change hasn't yet deployed to nightly from what I gather from here: https://prowlarr.servarr.com/v1/update/nightly/changes?runtime=netcore&os=linuxmusl

I'll come back after LS builds the nightly image.

**Comment by Qstick** [comment] 2022-12-20 22:37
Yea, the first go didn't fix it. Once I ran that sample response through the issue was pretty clear. While we originally set the title with the decoded variable, we ended up overwriting it later in the method with the original non-decoded property for certain movie cases.

**Comment by mynameisbogdan** [comment] 2022-12-20 22:40
Ah, I understand. Great news then. Thank you for taking the time to fix this. 👍
