### ISSUE TITLE
set download directory for qBittorrent

### ISSUE THREAD

**Issue by Jelmerb** [Prowlarr/Prowlarr#1091] opened 2022-08-10 18:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When I download anime, I don't want it to go in the default download directory and I can't change the default directory because Sonarr and Radarr depend on it. Sonarr and Radarr support for anime is slim, so I manage my anime shows outside of the root folder for tv shows and movies and because I want to keep them seperate. So I would like to download my anime shows straight to the anime folder. Sonarr and Radarr move the shows and movies to the respective root folders.

This is the folder structure:
- downloads (default download qBittorrent directory) 
- video
     - anime (desired custom download directory)
     - tv
     - movies
    

### Describe the solution you'd like

Transmission supports this behaviour but is not as capable as qBittorrent. qBittorrent handles categories differently than Transmission, it doesn't add a subdirectory, so I can't just use `anime` as the category with the default folder. 

### Describe alternatives you've considered

I have described some alternatives in the problem description.

### Anything else?

Just exactly what the advanced option `Directory` for Transmission does but for qBittorrent.

[AB#3449](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3449)

**Comment by bakerboy448** [comment] 2022-08-10 18:46
Duplicate of #170

**Closed by bakerboy448** 2022-08-10 18:46 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by bakerboy448** [comment] 2022-08-10 18:51
You configure the location of the category in qbit.

See TRaSH's guides for how to configure qbit.

Don't think there's any plans to specially allow setting a manual save path for every download....and per download category selection is probably the best it'll get.

**Comment by Jelmerb** [comment] 2022-08-10 18:54
sorry, I'll have a look a that. I really thought I did my homework before bothering you 😆. Thank you for taking the time to reply (and super fast!)
