### ISSUE TITLE
add torrentgalaxy error : query successfull but no result were returned from your indexer

### ISSUE THREAD

**Issue by tifo71** [Prowlarr/Prowlarr#2146] opened 2024-06-03 14:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When adding TorrentGalaxy on prowlarr there is an error
![image](https://github.com/Prowlarr/Prowlarr/assets/130233722/34ba7bd2-9ffb-422b-9c3a-e4c1257b2145)

### Expected Behavior

that adding torrentgalaxy works

### Steps To Reproduce

you need to add torrentgalaxy and the following error occurs during testing

### Environment

```markdown
- OS: windows 11 (openmediavault in virtual machine) 
- Prowlarr: 1.19.0.4545
- Docker Install: yes
- Using Reverse Proxy: yes
- Browser: opera one 110.0.5130.49
```

### What branch are you running?

Nightly

### Trace Logs?

[prowlarr.trace.txt](https://github.com/user-attachments/files/15535700/prowlarr.trace.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment] 2024-06-03 15:04
Duplicate of https://github.com/Prowlarr/Indexers/issues/459

**Closed by bakerboy448** 2024-06-03 15:04 UTC
Labels: Type: Bug, Status: Needs Triage
