### ISSUE TITLE
Ability to add generic RSS

### ISSUE THREAD

**Issue by muddro1** [Prowlarr/Prowlarr#1101] opened 2022-08-18 20:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Currently only way to add another site is to utilize Generic Tornznab, but not all sites support that. Would be great to just have the ability to add a generic rss feed just like sonarr/radarr Torrent RSS Feed option.

### Describe the solution you'd like

Adding a Generic Torrent RSS Feed modeled after sonarr/radarr

### Describe alternatives you've considered

can do individually in the arr itself, but thats the whole purpose of prowlarr, to centralize that. Also very handy for cross-seed.

### Anything else?

no

[AB#3477](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3477)

**Comment by bakerboy448** [comment] 2022-08-18 20:48
Duplicate of #248

**Closed by bakerboy448** 2022-08-18 20:48 UTC
Labels: Type: Feature Request, Status: Needs Triage
