### ISSUE TITLE
[FEAT]: RSS Feed, similar to Jackett

### ISSUE THREAD

**Issue by stevezau** [Prowlarr/Prowlarr#364] opened 2021-07-23 22:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

Hi, thank you all for the efforts on this project, it looks great.

I'm looking to migrate from Jackett. I use the API in Jacket to integrate into tools such as Flexget. (/api/v2.0/indexers/)

Does Prowlarr have an API/similar support?

Thanks

### Describe alternatives you've considered

N/A

### Anything else?

No

[AB#1284](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1284)

**Comment by bakerboy448** [comment] 2021-07-23 22:47
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/182

Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

like the other *arrs the entire UI is just lipstick on the API; watch the network calls in the browser dev console and go from there

**Closed by bakerboy448** 2021-07-23 22:47 UTC
Labels: Status: Needs Triage, Type: Feature Request

**Comment by stevezau** [comment] 2021-07-23 22:49
shit sorry, i swear i did search but obv not good enough,

**Comment by Qstick** [comment] 2021-07-23 22:52
Jackett RSS feed is just an empty torznab search, Prowlarr returns the same with something like this 

`http://192.168.1.160:9696/3/api?t=search&apikey={yourkey}`

**Comment by stevezau** [comment] 2021-07-23 22:53
great, ill test it, thanks

**Comment by stevezau** [comment] 2021-07-23 23:07
@Qstick can you also filter by category? I tried appending query param but it didn't seem to work.

categories=2000

**Comment by stevezau** [comment] 2021-07-23 23:08
Actually, when searchin hdbits i get unknown category "Please report this issue to the GitHub as this shouldn't be happening". Could be an issue with that indexer. ill report it when i get a sec

**Comment by Qstick** [comment] 2021-07-24 00:08
It would be cat=

Yea that might be an issue for that Indexer
