### ISSUE TITLE
[FEAT]: Dynamically filter the results

### ISSUE THREAD

**Issue by the-lazy-fox** [Prowlarr/Prowlarr#428] opened 2021-08-16 08:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

While looking for a movie, I need to filter down by keywords.

### Describe the solution you'd like

Like Jackett and HydraNZB, it would be awesome to have a field where we can type in to filter down the result without requesting a new search every time.

### Describe alternatives you've considered

Requesting a new search every time, painful and consuming API Hits.

### Anything else?

Thanks a lot!

[AB#1453](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1453)

**Comment by bakerboy448** [comment] 2021-08-16 08:32
Duplicate of #27

**Closed by bakerboy448** 2021-08-16 08:32 UTC
Labels: Type: Feature Request, Status: Needs Triage
