### ISSUE TITLE
When adding new tracker have option to filter already added ones

### ISSUE THREAD

**Issue by raidenlal** [Prowlarr/Prowlarr#764] opened 2022-01-07 12:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I use only public tracker torrents and those come and go and I remove old deprecated ones, but also add new ones. List of supported trackers is HUGE (thank you for that), there are several dropdowns for filtering by public/private or by language. So I will filter enUS, public, but the list is still huge and I have already forgotten which ones I have already added.

### Describe the solution you'd like

Could there be a filter for "show only not added trackers"?

Could the filtering options stay saved (within the browser session)? When adding multiple trackers you always need to re-input filters.

Or maybe like there is "mass edit" for existing ones there could be "mass add" from the filtered list of trackers?

### Describe alternatives you've considered

I have copied list from filtered trackers, then copied already added trackers and then did "diff" (compare) on those lists to discover which I am missing.

### Anything else?

IMHO Jackett has this "add new tracker" option more useful:

- when adding new tracker they hide all that were already added, so you see only missing ones (there might be usecase for having same tracker twice with different credentials, but I am not aware of any)
- when searching for a tracker they have name of tracker clickable, which leads to actual home page of the tracker
- when searching for a tracker they show tooltip with decription of given tracker - e.g. "this tracker is repository for legal open source projects" so you know if this makes sense or not for you

[AB#2323](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2323)

**Comment by bakerboy448** [comment] 2022-01-07 14:03
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/233

**Closed by bakerboy448** 2022-01-07 14:03 UTC
Labels: Type: Feature Request, Status: Needs Triage
