### ISSUE TITLE
[BUG]: windows - uninstall

### ISSUE THREAD

**Issue by thezoggy** [Prowlarr/Prowlarr#359] opened 2021-07-18 18:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Errors due to missing uninstaller
![prowlarr](http://zoggy.net/ApplicationFrameHost_2021-07-18_13-06-01.png)

### Expected Behavior

Uninstall

### Steps To Reproduce

Windows 10 install, then go uninstall

### Environment

```markdown
- OS: Windows 10
- Prowlarr: 0.1.0
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Any
```

### What branch are you running?

Develop

### Anything else?

See image

**Comment by bakerboy448** [comment] 2021-07-18 18:56
whats the full version w/ build number?

Could not reproduce this on a fresh develop (.608) Win10 install

Does that file truly no longer exist?

Given the absence of any other reports and the strange issues you were having with Radarr being unable to update as well; I think there are unknown, specific issues with your machine breaking *Arr updates and installs.

**Comment by thezoggy** [comment] 2021-07-18 19:52
yeah the file was not there, only .exe was normal main app+console and then the serviceinstall/serviceuninstall.  no unis*.exe
i already manually nuked the folder and everything for it so i cant share much more than that but all i did was grab the install from website and install then played with it for a day and realized it wasnt for me and now after a week wanted to clean it up.

looking back at my downloads i originally installed `Prowlarr.develop.0.1.0.361.windows-core-x64-installer.exe`

**Comment by bakerboy448** [comment] 2021-07-18 20:53
Closing Pending this being reproducible on current .6XX builds / additional reports

I'm thinking since again given Radarr v4 updates magically stopped working for you; you have some application mucking around with the files; an AV perhaps?

**Closed by bakerboy448** 2021-07-18 20:53 UTC
Labels: Status: Needs Triage, Status: Waiting For Info, Type: Bug

**Comment by thezoggy** [comment] 2021-07-18 22:46
no av/malware or anything like that on this box.  just re-installed and then could run the uninstaller just fine.  so no idea
