### ISSUE TITLE
No search results, but reports found: Specified key is not a valid size for this algorithm. (Parameter 'rgbKey')

### ISSUE THREAD

**Issue by andrewpong** [Prowlarr/Prowlarr#992] opened 2022-05-10 02:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Searching newznab for simple queries provides 0 results in the UI, even though results are returned from the service.

This is probably related to #963, but that one had Sonnar and Radarr in the mix - this issue occurs with both newznab and torrent indexers I have access to.

### Expected Behavior

Results returned from the service should be listed in the UI.

### Steps To Reproduce

1. Go to Search in the Prowlarr UI
2. Select Basic Search as the Query Options Search Type
3. Use a common term to test with (e.g. `ubuntu`)
4. Limit the Indexers to just 1
5. Click Search

### Environment

```markdown
- OS: Ubuntu 18.04.5 LTS
- Prowlarr: 0.3.0.1730
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Google Chrome 101.0.4951.54 (64-bit)
```

### What branch are you running?

Develop

### Trace Logs?

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/8657058/prowlarr.trace.txt)

```
2022-05-10 02:31:55.4|Debug|ReleaseSearchService|Total of 100 reports were found for Term: [ubuntu], Offset: 0, Limit: 100, Categories: [] from 1 indexer(s)
2022-05-10 02:31:55.4|Error|SearchController|Search failed: Specified key is not a valid size for this algorithm. (Parameter 'rgbKey')

[v0.3.0.1730] System.ArgumentException: Specified key is not a valid size for this algorithm. (Parameter 'rgbKey')
   at Internal.Cryptography.AesImplementation.CreateTransform(Byte[] rgbKey, Byte[] rgbIV, Boolean encrypting)
   at Internal.Cryptography.AesImplementation.CreateEncryptor(Byte[] rgbKey, Byte[] rgbIV)
   at NzbDrone.Core.Security.ProtectionService.Protect(String text) in D:\a\1\s\src\NzbDrone.Core\Security\ProtectionService.cs:line 31
   at NzbDrone.Core.Download.DownloadMappingService.ConvertToProxyLink(Uri link, String serverUrl, Int32 indexerId, String file) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadMappingService.cs:line 37
   at Prowlarr.Api.V1.Search.SearchController.MapDecisions(IEnumerable`1 releases, String serverUrl) in D:\a\1\s\src\Prowlarr.Api.V1\Search\SearchController.cs:line 159
   at Prowlarr.Api.V1.Search.SearchController.GetSearchReleases(SearchResource payload) in D:\a\1\s\src\Prowlarr.Api.V1\Search\SearchController.cs:line 137

2022-05-10 02:31:55.4|Trace|Http|Res: 42 [GET] /prowlarr/api/v1/search?query=ubuntu&indexerIds=1&type=search&limit=100&offset=0: 200.OK (930 ms)
```

[AB#3119](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3119)

**Comment by bakerboy448** [comment] 2022-05-13 13:27
Duplicate of #963

**Closed by bakerboy448** 2022-05-13 13:27 UTC
Labels: Type: Bug, Status: Needs Triage

**Comment by Qstick** [comment] 2022-05-13 23:02
Is your ApiKey different than the standard format @andrewpong?
