### ISSUE TITLE
Realtime search of query results

### ISSUE THREAD

**Issue by aronmgv** [Prowlarr/Prowlarr#1367] opened 2023-01-27 15:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I would like to perform real-time search of the results of the query output. E.g. I searched for "Frasier" sorted it by size. Now I want quickly analyze the results.. Sure I can do it with filters but that means I need to create a filter for every word I want to filter by.. I would rather have another search bar to do the real-time filter of the results.. you can keep filters as they are now but please introduce this real time search input.. it will help a lot to analyze the results.. Thanks.

### Describe the solution you'd like

See above.

### Describe alternatives you've considered

See above.

### Anything else?

See above.

[AB#4810](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4810)

**Comment by bakerboy448** [comment] 2023-01-27 17:11
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/735

**Closed by bakerboy448** 2023-01-27 17:11 UTC
Labels: Type: Feature Request, Status: Needs Triage
