### ISSUE TITLE
Issue Adding RetroFlix

### ISSUE THREAD

**Issue by Exile-boop** [Prowlarr/Prowlarr#1195] opened 2022-11-13 01:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When adding Retroflix it's returning this error: 
Unable to connect to the indexer. Unexpected response header text/html; charset=utf-8 from API request, expected application/json

I have included all the logs. 

### Expected Behavior

To accept and work 

### Environment

```markdown
- OS: 
- Prowlarr: 0.4.8.2072
- Docker Install: Yes
- Using Reverse Proxy: No 
- Browser:
```

### What branch are you running?

Develop

### Trace Logs?

https://privatebin.net/?9bfaefe311b0ef34#GRLW8xERya1kwUJK33ahbjb5aa9G2FedEgmuTfxwLoHz

[AB#4057](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4057)

**Comment by bakerboy448** [comment] 2022-11-13 01:56
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/1188

**Closed by bakerboy448** 2022-11-13 01:56 UTC
Labels: Type: Bug, Type: Duplicate
