### ISSUE TITLE
[Cardigann] TorrentLeech - Search by page/offset is not used in query to tracker

### ISSUE THREAD

**Issue by cfulton** [Prowlarr/Prowlarr#1428] opened 2023-02-15 07:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Searching from Sonarr for a season pack, the search takes significant time. 

Sonarr is running the query against Prowlarr for the TV Season, Prowlarr queries the tracker and returns the first 100 results. Sonarr then queries for the next 100 results, Prowlarr doesn't update the query to the tracker, tracker returns first 100 results again and Prowlarr returns that response. This results in Sonarr constantly searching each page as there is still 100 results. 

### Expected Behavior

Prowlarr when receiving a query for offset >= 100 to either return nothing; or 
Prowlarr when receiving a query for offset >= 100 to query for that offset to the tracker. 

### Steps To Reproduce

1. Ensure TorrentLeech profile setting "Default Number of Torrents per Page" is 100
2. Configure Prowlarr with TorrentLeech as an indexer
3. Configure Prowlarr with Sonarr as an app
4. From Sonarr, search a TV Season with the interactive search

You can observe the issue from the logs where each query is being made. 

### Environment

```markdown
- OS: Ubuntu 22.04
- Prowlarr: 1.2.0.2583
- Docker Install: YES
- Using Reverse Proxy: YES
- Browser: Chrome
```

### What branch are you running?

Develop

### Trace Logs?

Logs from Prowlarr:
https://privatebin.net/?aba4481d46692808#FJHJgBywhiFHPeZpXL1cmSmVzXdky3Lcf9xTi9AonGXx

Logs from Sonarr:
https://privatebin.net/?eee76b37f0970286#HGPZ8Kkgs819Qv8v3iUaWfmnD4kLdH7SHY8nuEndsxF5

**Comment by bakerboy448** [comment] 2023-02-15 12:47
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/379

**Closed by bakerboy448** 2023-02-15 12:47 UTC
Labels: Type: Bug, Status: Needs Triage

**Comment by bakerboy448** [comment] 2023-02-15 21:35
https://github.com/Sonarr/Sonarr/blob/279d3a89b6361f32142fcd33000ab0061eedbd94/src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs#L486-L496

looks like what's relevant for pagination?

Where's pagesize get set in Cardigann / prowlarr?

**Comment by bakerboy448** [comment] 2023-02-15 22:04
Just found that line.

so implementing pagination support into Cardigann / YML defs would resolve this issue as well, right?  This issue doesn't seem like it'd be limited to torrentleech and would be seen in any Cardigann tracker that has a hardcoded page # in the search query given its hardcoded to 1 for all

**Comment by bakerboy448** [comment] 2023-02-15 22:16
> Or maybe Sonarr should do a checksum check between pages?
> 
> https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Indexers/HttpIndexerBase.cs#L112-L178

Likely not a bad idea, but keep in mind Sonarr v3 was in beta for several years - no ETA when sonarr v4 may land as stable - so this annoyance could remain an issue for users for years.

For that prowlarr line for Cardigann - how many sites have multiple search paths that need to be hit?   Maybe it can be changed  to 100 until Cardigann is reworked to support proper pagination

**Comment by bakerboy448** [comment] 2023-02-15 22:31
So less than 10% have multiple search paths to hack their less than 100 results per page.

## option 1
- sonarr/radarr hash and compare the results stopping when they hit the same hash
- Cons: 
  - unsure of upstream buy-in
  - Long delay until the change would be in stable releases
- Pros:
  - not a prowlarr problem and stops erroneous starr pagination

## option 2
- add pagination (and offset) support to cardigann and rewrite all definitions
- pros:
  - proper and best solution
- cons:
  - heavy lift to rewrite prowlarr & jackett Cardigann logic + needing to review every tracker for pagesize and update search paths for pagination and offset

## option 3
- add pageSize support to Cardigann definitions (would be done as part of option 2 anyway)
- Pros:
  - fairly quick fix and can set Cardigann at default 100 then set those 44 definitions to their proper page size
- cons:
  - ????

## option 4
- prowlarr hash the results before returning them; if they are the same as the previous page, return no results
- Pros:
  - no Cardigann rework required
- cons:
  - performance?
  - ???
  - Feasibility?

**Comment by bakerboy448** [comment] 2023-02-27 01:30
https://github.com/Prowlarr/Prowlarr/commit/24f6c937da5670ae37d7683f986807b442a71f19
