### ISSUE TITLE
Ability to quick filter manual search results within Prowlarr

### ISSUE THREAD

**Issue by DrFrankensteinUK** [Prowlarr/Prowlarr#1298] opened 2023-01-06 22:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Before migrating to Prowlarr about 18 months or so ago I made extensive use of NZBHydra2 this had a post search filter that allowed you to fine tune what could be pages of results depending on the search query. 

Seen in the example attached my search result of 'Baking' returns 2900 results from a single indexer, but the quick filter allowed me to get what I really wanted which was gingerbread. :)

In a normal search some public torrent trackers return a lot of bizarre results depending on your search terms so a quick way to filter out the results would be great.

### Describe the solution you'd like

It would be great if after the search results are displayed there was a quick filter box that behaved similarly to the one on Hydra2. Thus allowing you to fine tune the terms used and quickly grab what you were actually after. 

### Describe alternatives you've considered

The alternative is to use the existing custom filters however for the above example this would require multiple steps for what would be likely a one-off search. Also, I tried just using Ctrl+F however this is not functional past the first 'page' of results as they are not considered as on the screen.

Thanks for your consideration

### Anything else?

![hydra example](https://user-images.githubusercontent.com/4955335/211108121-92549260-87e7-423a-8ba3-cfc2a4f61aba.gif)

[AB#4655](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4655)

**Comment by bakerboy448** [comment] 2023-01-06 22:16
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/735
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/27 - Manual Searching 1 and 12

**Closed by bakerboy448** 2023-01-06 22:16 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by DrFrankensteinUK** [comment] 2023-01-06 22:22
Well clearly I am blind! Sorry for wasting time!
