### ISSUE TITLE
Filter indexers out of Add Indexer search if currently configured

### ISSUE THREAD

**Issue by lordyod** [Prowlarr/Prowlarr#776] opened 2022-01-12 21:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Not a problem, UI enhancement.

### Describe the solution you'd like

If I already have an indexer configured, then I should be able to filter it out of the list of indexers shown in the Add Indexer dialogue. I'm not aware of a use case for configuring an indexer multiple times but assuming that there is one, a toggle to hide/show already-configured indexers would work.

### Describe alternatives you've considered

A setting toggle in the UI settings or within the Add Indexer dialogue itself would work.

### Anything else?

N/A

[AB#2360](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2360)

**Comment by bakerboy448** [comment] 2022-01-12 22:24
Duplicate of several other issues.

**Closed by bakerboy448** 2022-01-12 22:24 UTC
Labels: Type: Feature Request, Status: Needs Triage
