### ISSUE TITLE
Map categories based on priv/public trackers and choose download client based on categories

### ISSUE THREAD

**Issue by Brandoskey** [Prowlarr/Prowlarr#1415] opened 2023-02-09 15:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I run two instances of deluge, one for movies and one for tv due to libraries being split between devices and the desire to utilize hardlinks/atomic moves on both libraries. These instances of deluge also have labels based on private and public trackers

examples: tv for public trackers and tv-ipt for private trackers for seed ratio purposes. Same thing for the movies client

### Describe the solution you'd like

A dropdown or dialog popup that could be displayed when selecting items to download that allows me to specify which download client to use and catagory to use

Alternatively beefing up the current category mapping to choose the download client based on category tags and to alter those tags based on private/public trackers

### Describe alternatives you've considered

Running a third client just for prowlarr grabs, but that wouldn't solve the hardlinks/atomic moves issue for both data stores

### Anything else?

Here's the workflow I'm thinking to automate the process

example: 
Tracker > Grab cat. > Download client cat.  > Download client

Private tracker > tv >  priv-tv > Deluge TV     <--Private tracker alters category and that category determines download client 
Public tracker > movie > movie > Deluge Movie <--category unaltered for public tracker and category determines download client

Also, thanks for your consideration
         

[AB#4889](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4889)

**Comment by bakerboy448** [comment] 2023-02-09 16:19
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/1005

**Closed by bakerboy448** 2023-02-09 16:19 UTC
Labels: Type: Feature Request, Status: Needs Triage
