### ISSUE TITLE
M-Team redirected to Google

### ISSUE THREAD

**Issue by Gladtbam** [Prowlarr/Prowlarr#1776] opened 2023-07-12 03:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

M-Team has not been working properly for almost a month, I added it again and it shows redirected to google.com

`Unable to connect to indexer. Redirected to https://www.google.com/torrents.php?cat401=1&cat419=1&cat420=1&cat421=1&cat439=1&cat403=1&cat402=1&cat435=1&cat438=1&cat404=1&cat405=1&cat407=1&cat422=1&cat423=1&cat427=1&cat409=1&search=&incldead=0&spstate=0&search_area=0&search_mode=0&sort=4&type=desc&notnewword=1 from indexer request`

### Expected Behavior

should redirect correctly

### Steps To Reproduce

1. I removed the old FlareSolverr Docker image and pulled the newest (Vsersion: 3.2.1).
2. Reset the indexer proxy, the test is valid.
3. Re-add M-team

### Environment

```markdown
- OS: Debian GNU/Linux 11 (bullseye)
- Prowlarr: 1.6.3.3608
- Docker Install: No
- Using Reverse Proxy: Flaresolverr
- Browser: Firefox 114.0.2
```

### What branch are you running?

Master

### Trace Logs?

**Flaresolverr Docker logs did not add m-team's log**
```
Got redirected to another domain. Try changing the indexer URL to https://www.google.com/.
```
```
Redirected to https://www.google.com/torrents.php?cat401=1&cat419=1&cat420=1&cat421=1&cat439=1&cat403=1&cat402=1&cat435=1&cat438=1&cat404=1&cat405=1&cat407=1&cat422=1&cat423=1&cat427=1&cat409=1&search=&incldead=0&spstate=0&search_area=0&search_mode=0&sort=4&type=desc&notnewword=1 from indexer request
```
```
Unable to connect to indexer: Redirected to https://www.google.com/torrents.php?cat401=1&cat419=1&cat420=1&cat421=1&cat439=1&cat403=1&cat402=1&cat435=1&cat438=1&cat404=1&cat405=1&cat407=1&cat422=1&cat423=1&cat427=1&cat409=1&search=&incldead=0&spstate=0&search_area=0&search_mode=0&sort=4&type=desc&notnewword=1 from indexer request

NzbDrone.Core.Indexers.Exceptions.IndexerException: Redirected to https://www.google.com/torrents.php?cat401=1&cat419=1&cat420=1&cat421=1&cat439=1&cat403=1&cat402=1&cat435=1&cat438=1&cat404=1&cat405=1&cat407=1&cat422=1&cat423=1&cat427=1&cat409=1&search=&incldead=0&spstate=0&search_area=0&search_mode=0&sort=4&type=desc&notnewword=1 from indexer request
   at NzbDrone.Core.Indexers.Definitions.Cardigann.CardigannParser.ParseResponse(IndexerResponse indexerResponse) in ./Prowlarr.Core/Indexers/Definitions/Cardigann/CardigannParser.cs:line 55
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 444
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 687
```
```
FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer. Redirected to https://www.google.com/torrents.php?cat401=1&cat419=1&cat420=1&cat421=1&cat439=1&cat403=1&cat402=1&cat435=1&cat438=1&cat404=1&cat405=1&cat407=1&cat422=1&cat423=1&cat427=1&cat409=1&search=&incldead=0&spstate=0&search_area=0&search_mode=0&sort=4&type=desc&notnewword=1 from indexer request: Validation failed: 
 -- : Unable to connect to indexer. Redirected to https://www.google.com/torrents.php?cat401=1&cat419=1&cat420=1&cat421=1&cat439=1&cat403=1&cat402=1&cat435=1&cat438=1&cat404=1&cat405=1&cat407=1&cat422=1&cat423=1&cat427=1&cat409=1&search=&incldead=0&spstate=0&search_area=0&search_mode=0&sort=4&type=desc&notnewword=1 from indexer request

FluentValidation.ValidationException: Validation failed: 
 -- : Unable to connect to indexer. Redirected to https://www.google.com/torrents.php?cat401=1&cat419=1&cat420=1&cat421=1&cat439=1&cat403=1&cat402=1&cat435=1&cat438=1&cat404=1&cat405=1&cat407=1&cat422=1&cat423=1&cat427=1&cat409=1&search=&incldead=0&spstate=0&search_area=0&search_mode=0&sort=4&type=desc&notnewword=1 from indexer request
   at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in ./Prowlarr.Api.V1/ProviderControllerBase.cs:line 212
   at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in ./Prowlarr.Api.V1/ProviderControllerBase.cs:line 198
   at Prowlarr.Api.V1.ProviderControllerBase`3.CreateProvider(TProviderResource providerResource, Boolean forceSave) in ./Prowlarr.Api.V1/ProviderControllerBase.cs:line 69
   at lambda_method617(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Prowlarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Prowlarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

```
Invalid request Validation failed: 
 -- : Unable to connect to indexer. Redirected to https://www.google.com/torrents.php?cat401=1&cat419=1&cat420=1&cat421=1&cat439=1&cat403=1&cat402=1&cat435=1&cat438=1&cat404=1&cat405=1&cat407=1&cat422=1&cat423=1&cat427=1&cat409=1&search=&incldead=0&spstate=0&search_area=0&search_mode=0&sort=4&type=desc&notnewword=1 from indexer request
```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment] 2023-07-12 03:39
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/1061

**Closed by bakerboy448** 2023-07-12 03:39 UTC
Labels: Type: Bug, Status: Needs Triage

**Comment by Gladtbam** [comment] 2023-07-12 06:21
![图片](https://github.com/Prowlarr/Prowlarr/assets/49943258/cefa2b70-5f33-4e96-b424-95ccbe2689b0)

On the same server as prowlarr, I successfully added the M-Team using Jackett and the search is also available

**Comment by Gladtbam** [comment] 2023-07-12 06:30
[prowlarr.debug.txt](https://github.com/Prowlarr/Prowlarr/files/12024515/prowlarr.debug.txt)
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/12024517/prowlarr.trace.txt)

**Comment by ohsc** [comment] 2023-08-10 08:47
I have the same issue. I noticed that Prowlarr doesn't invoke Flaresolverr after matching the tag. Flaresolverr doesn't have any invocation logs. However, everything works fine when I switch to Jackett, and Flaresolverr has invocation logs.

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/12310819/prowlarr.trace.txt)
[prowlarr.debug.txt](https://github.com/Prowlarr/Prowlarr/files/12310820/prowlarr.debug.txt)

**Comment by bakerboy448** [comment] 2023-08-10 08:50
Please do not spam closed duplicate issues.

this is a tracker problem that has no resolution for prowlarr - they hate automation
