### ISSUE TITLE
[FEAT]: Causing an error by clicking "test" prevents saving indexer.

### ISSUE THREAD

**Issue by chazlarson** [Prowlarr/Prowlarr#581] opened 2021-11-04 15:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The "Save" button won't work if the "test" button has generated an error.  In reproducing it to get logs, it seems that sometimes it doesn't save due to the error even if no failing "test" is done.

### Expected Behavior

I would expect the save button to work the same in either case.  Just because the test failed doesn't mean I don't want to save.  I'd expect the equivalent of Hydra's "I know what I'm doing, save anyway"

### Steps To Reproduce

DOGnzb has exhausted its 100 daily hits and is showing an error.  
Click the edit icon to bring up the indexer edit dialog
Enter "100" in the daily limit field, and click "test".
The test fails and displays an error.  Not unexpected.  
Click "Save".  Save fails and show the same error.

Close the dialog and reopen it
Enter the "100" and click save *first*.  
The indexer config is saved without error and the dialog closes.

### Environment

```markdown
- OS: Ubuntu 20.04
- Prowlarr: 0.1.1.1030
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Microsoft Edge Version 95.0.1020.40 (Official build) (x86_64)
```

### What branch are you running?

Develop

### Anything else?

When I generated these logs, I went through the process above, changing the daily limit from 100 to 101.  Then I tried to change it back to 100 [without testing first], and got the same error, so the issue does not appear to be entirely related to clicking test first.

[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/7475829/prowlarr.trace.txt)
[prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/7475830/prowlarr.txt)
[prowlarr.debug.txt](https://github.com/Prowlarr/Prowlarr/files/7475831/prowlarr.debug.txt)

[AB#1865](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1865)

**Comment by bakerboy448** [comment] 2021-11-04 15:16
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/572

and several others.  572 has the link to the comment with the workaround for how to save failing indexers

**Closed by bakerboy448** 2021-11-04 15:16 UTC
Labels: Type: Bug, Status: Needs Triage
