### ISSUE TITLE
Do not overwrite an indexer's download client in Radarr with full sync

### ISSUE THREAD

**Issue by akesher123** [Prowlarr/Prowlarr#1209] opened 2022-11-24 04:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Somewhat. If you specify a download client for an indexer in Radarr and have full sync level set in Prowlarr, Prowlarr will overwrite the download client. I'm not sure if people consider this a "problem" or a feature.

### Describe the solution you'd like

Since the download client is not specifiable in Prowlarr, I think that it should keep from overwriting this field. In full sync, Prowlarr essentially operates as the main source of truth. Radarr should act as a secondary source of truth. If Prowlarr has a field set, it should overwrite that field in Radarr. If it doesn't have any information on that field, it should logically delegate that decision to Radarr instead of telling it to wipe the setting to default.

### Describe alternatives you've considered

I've considered using add and remove only sync level. This would work, but I like Prowlarr to be where I configure the behavior of the indexers. If I changed priority or seed time, for example, these would not propagate to Radarr without a manual sync.

### Anything else?

It looks like the Radarr API supports specifying a `downloadClientId` I'm not sure what's being passed there, but I assume it's 0, or whatever selects the "Any" indexer.

Two possible solutions could be to either

-  make this nullable on the Radarr side, then pass nothing from prowlarr (or pass something like -1 if a nullable into param isn't possible in )
- fetch info about the remote indexer first, then pass any values that prowlarr won't be overriding back over the same as they were.

[AB#4151](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4151)

**Comment by bakerboy448** [comment] 2022-11-24 04:03
Duplicate of #1165

**Closed by bakerboy448** 2022-11-24 04:03 UTC
Labels: Type: Feature Request, Type: Duplicate
