### ISSUE TITLE
Althub config may be wrong

### ISSUE THREAD

**Issue by AtariBaby** [Prowlarr/Prowlarr#1013] opened 2022-05-23 17:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I tried to add altHUB, the api url was wrong. i got an error. I used what is on their config page and it worked.

### Expected Behavior

The fix is to use https://api.althub.co.za/ (not the one listed in prowlarr) and keep /api in the field below it. Then it worked.

I also changed the prowlar config to “shown” and added the limits, so it’s possible this was a requirement? But I think using the url they recommend is the fix.

### Steps To Reproduce

Self explanatory above. Your default config seems to contain the wrong url.

### Environment

```markdown
- OS: Win 10 Pro
- Prowlarr: 0.3.0.1730
- Browser: iPadOS Safari
```

### What branch are you running?

Develop

### Trace Logs?

2022-05-23 10:01:59.3|Warn|IndexerHttpClient|HTTP Error - Res: [GET] https://althub.co.za/api?t=caps&apikey=(removed) 403.Forbidden
2022-05-23 10:01:59.3|Warn|Newznab|Unable to connect to indexer

[AB#3182](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3182)

**Comment by bakerboy448** [comment] 2022-05-23 17:52
Duplicate of #1012

**Comment by bakerboy448** [comment] 2022-05-23 17:52
Already fixed in nightly
https://github.com/Prowlarr/Prowlarr/commit/ed46c5c86d24d8a5a57bfd7a21cb5a865f7406bf

**Closed** 2022-05-23 17:53 UTC
Labels: Type: Bug, Type: Duplicate
