### ISSUE TITLE
[BUG]: Some Cardigann Indexers with Supported Categories not Syncing to Apps

### ISSUE THREAD

**Issue by IsusVonBier** [Prowlarr/Prowlarr#517] opened 2021-09-29 08:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Full sync for both radarr and sonarr are turned on.  These indexers are not syncing to apps. They work in prowlarr search, and they work when added from jackett.

Radarr: ACGsou, BinSearch, LimeTorrents, Torrentz2eu
Sonarr: BinSearch, LimeTorrents, Torrentz2eu (_ACG is synced to sonarr_)

Categories:
ACGsou: Audio, Books, Movies, Other, PC, TV
BinSearch: None
LimeTorrents: Audio, Console, Movies, Other, PC, TV
Torrentz2eu: Movies, Other, TV

### Expected Behavior

For them to sync to apps.

### Environment

```markdown
- OS: Raspberry Pi OS Lite, Linux 5.10.60-v7l+
- Prowlarr: 0.1.1.953 nightly-55d413a by hotio
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser:
```

### What branch are you running?

Nightly

### Anything else?

I'm not sure if these are required logs:

```2021-09-29 10:13:10.4|Info|Cardigann|Adding request: https://www.36dm.club/1.html
2021-09-29 10:13:42.1|Info|NzbSearchService|Searching indexers: [LimeTorrents] for {Term: , Offset: 0, Limit: 100, Categories: [5000, 5070]}
2021-09-29 10:13:42.1|Info|Cardigann|Adding request: https://www.limetorrents.pro/latest100
2021-09-29 10:13:42.9|Warn|HttpClient|HTTP Error - Res: [POST] http://192.168.13.15:8989/api/v3/indexer: 400.BadRequest
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]
2021-09-29 10:13:42.9|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService HTTP request failed: [400:BadRequest] [POST] at [http://192.168.13.15:8989/api/v3/indexer]
2021-09-29 10:13:44.2|Info|NzbSearchService|Searching indexers: [Torrentz2eu] for {Term: , Offset: 0, Limit: 100, Categories: [5000]}
2021-09-29 10:13:44.2|Info|Cardigann|Adding request: https://torrentz2.unblockninja.com/kick.php?q=2021
2021-09-29 10:13:44.5|Warn|HttpClient|HTTP Error - Res: [POST] http://192.168.13.15:8989/api/v3/indexer: 400.BadRequest
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]
2021-09-29 10:13:44.6|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService HTTP request failed: [400:BadRequest] [POST] at [http://192.168.13.15:8989/api/v3/indexer]
2021-09-29 10:13:46.2|Info|NzbSearchService|Searching indexers: [Miatrix] for {Term: , Offset: 0, Limit: 100, Categories: [5000, 5020, 5040, 5050, 5030, 5045, 5010, 5070]}
2021-09-29 10:13:57.1|Info|NzbSearchService|Searching indexers: [LimeTorrents] for {Term: , Offset: 0, Limit: 100, Categories: [2000]}
2021-09-29 10:13:57.1|Info|Cardigann|Adding request: https://www.limetorrents.pro/latest100
2021-09-29 10:13:57.9|Warn|HttpClient|HTTP Error - Res: [POST] http://192.168.13.15:7878/api/v3/indexer: 400.BadRequest
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]
2021-09-29 10:13:58.0|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService HTTP request failed: [400:BadRequest] [POST] at [http://192.168.13.15:7878/api/v3/indexer]
2021-09-29 10:13:59.1|Info|NzbSearchService|Searching indexers: [Torrentz2eu] for {Term: , Offset: 0, Limit: 100, Categories: [2000]}
2021-09-29 10:13:59.1|Info|Cardigann|Adding request: https://torrentz2.unblockninja.com/kick.php?q=2021
2021-09-29 10:13:59.4|Warn|HttpClient|HTTP Error - Res: [POST] http://192.168.13.15:7878/api/v3/indexer: 400.BadRequest
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]
2021-09-29 10:13:59.5|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService HTTP request failed: [400:BadRequest] [POST] at [http://192.168.13.15:7878/api/v3/indexer]
2021-09-29 10:14:01.1|Info|NzbSearchService|Searching indexers: [ACGsou] for {Term: , Offset: 0, Limit: 100, Categories: [2000, 2020]}
2021-09-29 10:14:01.1|Info|Cardigann|Adding request: https://www.36dm.club/1.html
2021-09-29 10:14:02.9|Warn|HttpClient|HTTP Error - Res: [POST] http://192.168.13.15:7878/api/v3/indexer: 400.BadRequest
[
  {
    "isWarning": false,
    "propertyName": "",
    "errorMessage": "Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.",
    "severity": "error"
  }
]
2021-09-29 10:14:02.9|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService HTTP request failed: [400:BadRequest] [POST] at [http://192.168.13.15:7878/api/v3/indexer]
2021-09-29 10:14:03.2|Info|NzbSearchService|Searching indexers: [Miatrix] for {Term: , Offset: 0, Limit: 100, Categories: [2000, 2050, 2060, 2070, 2010, 2040, 2020, 2030, 2045]}
2021-09-29 10:14:15.3|Warn|HttpClient|HTTP Error - Res: [POST] http://192.168.13.15:7878/api/v3/indexer: 400.BadRequest
[
  {
    "propertyName": "Name",
    "errorMessage": "Should be unique",
    "attemptedValue": "Rarbg (Prowlarr)",
    "severity": "error",
    "errorCode": "PredicateValidator",
    "formattedMessageArguments": [],
    "formattedMessagePlaceholderValues": {
      "propertyName": "Name",
      "propertyValue": "Rarbg (Prowlarr)"
    }
  }
]
2021-09-29 10:14:15.4|Warn|ApplicationService|NzbDrone.Core.Applications.ApplicationService HTTP request failed: [400:BadRequest] [POST] at [http://192.168.13.15:7878/api/v3/indexer]
```

[AB#1615](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1615)

**Comment by bakerboy448** [comment] 2021-09-29 18:57
Checked LimeTorrents.

This is some critical info from trace logs (which should be provided for all bug reports)

```
2021-09-29 13:47:31.6|Trace|Cardigann|.Config.info_8000 got value "LimeTorrents only returns category <b>Other</b> in its <i>Keywordless</i> search results page.</br>To pass your apps' indexer TEST you will need to include the 8000(Other) category."
2021-09-29 13:47:31.6|Debug|Cardigann|Setting info_8000 to LimeTorrents only returns category <b>Other</b> in its <i>Keywordless</i> search results page.</br>To pass your apps' indexer TEST you will need to include the 8000(Other) category.
```

Appears all noted indexers have the same/similar notes
https://github.com/search?q=8000%28Other%29+repo%3AProwlarr%2FIndexers+path%3A%2Fdefinitions%2Fv1&type=Code&ref=advsearch&l=&l=

Torrentz2Eu likely needs to be re-thought, perhaps we need a sync exemption somehow.

`    default: Torrentz2eu does not display categories in its search results page. This definition is probably only suitable for Jackett Dashboard Manual searches.`


It is not expected for BinSearch to sync given it has no categories. 


- [ ] -  ACGsou: Audio, Books, Movies, Other, PC, TV
  -  Needs review
- [X] - BinSearch: None
  -  Will not be synced. Refer to https://github.com/Prowlarr/Prowlarr/issues/394
- [ ] -  LimeTorrents: Audio, Console, Movies, Other, PC, TV
  -  Will not sucessfully be synced. Due to absence of categories.
  - `LimeTorrents only returns category <b>Other</b> in its <i>Keywordless</i> search results page.</br>To pass your apps's indexer TEST you will need to include the 8000(Other) category.`
  - Possibly would be fixed by Refer to https://github.com/Prowlarr/Prowlarr/issues/394
- [ ] -  Torrentz2eu: Movies, Other, TV
  -  Will not successfully be synced. Due to absence of categories.
  - `Torrentz2eu does not display categories in its search results page. This definition is probably only suitable for Jackett Dashboard Manual searches.`
  - `  # unfortunately torrentz2eu does not display categories anywhere in its search results page :-(`

**Comment by Gareth4321** [comment] 2022-01-04 14:37
I am also experiencing this issue with Torrentz2 specifically, and reviewing the logs, it appears for the same reason.

**Comment by SteffanCline** [comment] 2022-02-09 19:56
I have also received this error on 3D torrents and a couple others. Is there something I can do to fix it?

**Comment by hchapman1089** [comment] 2022-05-02 12:38
I am saving a similar issue when adding a new indexer to Sonarr or Radarr.....

**Comment by bakerboy448** [comment] 2022-05-02 14:10
Without specifying what tracker is failing - additional comments indicating trackers are not syncing are not productive.

So far every single instance reported has been \*Arrs correctly rejecting the add attempt because the indexer's rss test feed fails to contain any torrents in the configured categories for \*Arr.

These indexers can be manually in \*Arr and will likely need to be force added. (Saved Twice)

Given that the issue is not Prowlarr and with the trackers not returning the appropriate results to sync - that is not something Prowlarr has any control over.

Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

Closing for now.  Tagging for future consideration of some force-sync option.
Alternatively, it's an advanced setting within each app in prowlarr for what categories to add / use.

**Closed by bakerboy448** 2022-05-02 14:10 UTC
Labels: Type: Bug
