### ISSUE TITLE
Allow for Infinite seeding (-1)

### ISSUE THREAD

**Issue by Minituff** [Prowlarr/Prowlarr#2194] opened 2024-08-07 23:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues
- I do see a related issue for this https://github.com/Prowlarr/Prowlarr/issues/1990 , but I don't understand the workaround since I cannot set -1 in qbit

### Is your feature request related to a problem? Please describe

I can't set seed limits except more than 0. This means there MUST be some sort of limit on seeding.

I cannot set the value to `-1` in qbit otherwise the feature gets disable then then all seeding limits do not get passed into qbit.

This is what happens when I click save:
<img width="538" alt="CAnt set to 0" src="https://github.com/user-attachments/assets/89aec026-883c-43f5-9af6-64dc16492f03">

I *must* have these boxes check for the sonarr/radarr to send ratio/time limits to qbit.

### Describe the solution you'd like

Allow for a setting of `-1` for infinite seeding.

### Describe alternatives you've considered

I possibly could use something like Qbitmange?

**Comment by bakerboy448** [comment] 2024-08-07 23:05
Duplicate of #1990

**Closed by bakerboy448** 2024-08-07 23:05 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by Minituff** [comment] 2024-08-07 23:14
Okay I understand now. I was able to get it working using this method.

* You can set a value to `-1`, you will just get a warning, but you can **press save anyway.**
![image](https://github.com/user-attachments/assets/5b8019df-7116-4676-b32c-71bb59304d5a)

I can confirm this is working in Qbit. Thank you.

**Comment by aqsede** [comment] 2024-09-02 09:38
In transmission it goes to 65535 only (around 45 Days) , if I set to 999eˣ..(Xunlimited) it will be assuming app default
I want some tracker to be able to set to unlimited, but not default on all app...

![image](https://github.com/user-attachments/assets/f0b22135-1789-458f-86e5-116970e16046)

![image](https://github.com/user-attachments/assets/f0a22cdb-1afd-4cc0-b656-2313e2c29bab)

**Comment by bakerboy448** [comment] 2024-09-02 20:57
Please don't comment on unrelated issues.

if there are issues with Starr implementations of transmission they need to be fixed in Starr.

Prowlarr has nothing to do with how Starr interact with transmission or what limits are set
