### ISSUE TITLE
Push and Sync Download Clients

### ISSUE THREAD

**Issue by S4lmify** [Prowlarr/Prowlarr#1190] opened 2022-11-09 15:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

With using multiple apps like radarr, sonarr, readarr, lidarr, and others comes syncing and adding download clients to all of them. Sometimes multiple times if you use a usenet client and a torrent client. 

### Describe the solution you'd like

It would be a nice QOL feature to be able to have prowlarr manage your download clients. Less area for mistakes when managing multiple clients and apps.

### Describe alternatives you've considered

Manually adding download clients

### Anything else?

n/a

[AB#4049](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4049)

**Comment by bakerboy448** [comment] 2022-11-09 15:23
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/583
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/509
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/323

![1F4C40B9-2060-48C7-B9FB-585550F09AF2](https://user-images.githubusercontent.com/55419169/200870196-23ef3227-5a20-450a-93fa-e180c0829723.jpeg)
Please search next time

**Closed by bakerboy448** 2022-11-09 15:23 UTC
Labels: Type: Feature Request, Area: Download Clients, Type: Duplicate
