### ISSUE TITLE
Propagated Tags Field

### ISSUE THREAD

**Issue by adventiar** [Prowlarr/Prowlarr#1216] opened 2022-11-26 21:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Full sync is awesome because it allows you to control the indexers from one central place. In my use case the only thing would change per client (and need to do so on all clients) is adding tags. There are many indexers that only find anime. But Radarr and Sonarr both can be used for more than Anime Movies/Tv Shows. 

A user can tag the indexer (in Sonarr/Radarr) with say "Anime" then tag all anime with this tag as well. This allows those indexers to only be used by Shows/Movies that results can be found for.

However when using full sync it will remove those tags from the indexer when it is synced. This means you either don't use full sync and lose the benifits from it, only add the Anime indexers to the app itself (don't use prowlarr at all for them) or allow Anime only indexer to be searched when looking for non-anime content.

### Describe the solution you'd like

I think it would be great if Prowlarr had a field that allows the user to specify tags to be synced to the apps. This way the user could tag the indexer in Prowlarr and it will already be tagged in any app that it is synced to. This fully distinguishes the indexer as an Anime Only indexer.

### Describe alternatives you've considered

Another possibly simpler solution could be to make it so that indexer tags in the app (Sonarr/Radarr) are not cleared on full sync. Prowlarr isn't syncing tags anyway so why remove the local tags placed? This is also true for other settings as well like "Minimum seeders" for example.

### Anything else?

I am not sure how much value this has outside of my anime example. But it can be frustrating to have Prowlarr remove values from settings it does not control. This is especially true when it's a setting you want across all apps. 

I really want to take advantage of full sync, but this issue makes it so that it must be disabled across all my apps to not hit indexers for no good reason.

[AB#4182](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4182)

**Comment by bakerboy448** [comment] 2022-11-26 21:54
Duplicate of #500

please  search next time rather than merely checking the box
https://github.com/Prowlarr/Prowlarr/issues?q=is%3Aissue+is%3Aopen+tags

**Closed by bakerboy448** 2022-11-26 21:54 UTC
Labels: Type: Feature Request, Type: Duplicate

**Comment by adventiar** [comment] 2022-11-26 21:58
@bakerboy448 my apologies I did filter by feature request tag and look. I see it is there but didn't notice originally so it was an oversight on my part. I did look though I would never "just check the box" we all make mistakes.
