### ISSUE TITLE
[FEAT]: Choose with category to use when manually downloading a file

### ISSUE THREAD

**Issue by the-lazy-fox** [Prowlarr/Prowlarr#412] opened 2021-08-10 21:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I'm downloading with SABNzdb where I have several categories for severals purposes.
Folder, post processing, notifications are not the same depending on that.

When I configure a downloader, I must select a category and only one.

### Describe the solution you'd like

It would be great to be able to select the category we want to use while pushing the file to the downloader

### Describe alternatives you've considered

As an alternative, I made one client per category (a bit overkill) but when I select the downloader button in the result list, it takes the first one by default.
An alternative would be to have a dropdown list of downloaders compatible with this protocol and then settings up one per category.

### Anything else?

In the end, both ways can have pro and cons, then I would ultimately suggests to:

- Be able to list more than one category for the downloader
- If there is more than one compatible downloader for that file protocol, display a dropdown list next to the download button
- If there is more than one category configured for that downloader, display a dropdown list next to the download button

Cheers

**Comment by bakerboy448** [comment] 2021-08-10 21:12
Duplicate of #170

[Please actually search prior to opening duplicates and don't just check the box claiming you did.](https://github.com/Prowlarr/Prowlarr/issues?q=is%3Aissue+is%3Aopen+category)

**Closed by bakerboy448** 2021-08-10 21:12 UTC
Labels: Type: Feature Request, Status: Needs Triage

**Comment by the-lazy-fox** [comment] 2021-08-10 21:15
Sorry for that, missed it.
Thanks for the link!
