### ISSUE TITLE
Number of Seeders and Ratio Options For Torrent Indexers

### ISSUE THREAD

**Issue by mattyteds** [Prowlarr/Prowlarr#800] opened 2022-01-25 03:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Depending on torrent indexer I have different thresholds for seeind. I also have a minimum limit of seeders before grabbing a torrent. Sonarr and Radarr both have these options and support this. When pushing from Prowlarr these are not filled in leading to them being blank which leads to unwanted default settings on the client.

### Describe the solution you'd like

Being able to set the number of seeds, seed ratio and seed ratio per torrent indexer.

### Describe alternatives you've considered

n/a

### Anything else?

n/a

[AB#2496](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2496)

**Comment by bakerboy448** [comment] 2022-01-25 03:48
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/106

**Closed by bakerboy448** 2022-01-25 03:48 UTC
Labels: Type: Feature Request, Status: Needs Triage
