### ISSUE TITLE
Yggtorrent 503.ServiceUnavailable

### ISSUE THREAD

**Issue by Oz246** [Prowlarr/Prowlarr#708] opened 2021-12-13 08:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello I am having a problem with the configuration of Yggtorrent : 

Yggtorrent 503.ServiceUnavailable

### Expected Behavior

Hello I am having a problem with the configuration of Yggtorrent : 

Yggtorrent 503.ServiceUnavailable

### Environment

```markdown
- OS: 
- Prowlarr:0.1.8.1231
- Docker Install: Np
- Using Reverse Proxy: No
- Browser: Google chrome
```

### What branch are you running?

Develop

### Trace Logs?

<html>
<body>

9:45am | ProwlarrErrorPipeline | FluentValidation.ValidationException: Validation failed: -- : Unable to connect to indexer, check the log for more details at Prowlarr.Api.V1.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 200 at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 191 at Prowlarr.Api.V1.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Prowlarr.Api.V1\ProviderControllerBase.cs:line 140 at lambda_method86(Closure , Object , Object[] ) at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync() at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync() --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync() --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited\|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger) at Prowlarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\BufferingMiddleware.cs:line 28 at Prowlarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\IfModifiedMiddleware.cs:line 41 at Prowlarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33 at Prowlarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\UrlBaseMiddleware.cs:line 27 at Prowlarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Prowlarr.Http\Middleware\VersionMiddleware.cs:line 28 at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context) at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult) at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited\|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task): Validation failed: -- : Unable to connect to indexer, check the log for more details |  
-- | -- | -- | --
  | 9:45am | Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware | An unhandled exception has occurred while executing the request.: Validation failed: -- : Unable to connect to indexer, check the log for more details |  
  | 9:45am | Cardigann | Unable to connect to indexer: HTTP request failed: [503:ServiceUnavailable] [GET] at [https://www3.yggtorrent.re/] |  
  | 9:45am | IndexerHttpClient | HTTP Error - Res: [GET] https://www3.yggtorrent.re/: 503.ServiceUnavailable <!DOCTYPE HTML> <html lang="en-US"> <head> <meta charset="UTF-8" /> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" /> <meta name="robots" content="noindex, nofollow" /> <meta name="viewport" content="width=device-width,initial-scale=1" /> <title>Just a moment...</title> <style type="text/css"> html, body {width: 100%; height: 100%; margin: 0; padding: 0;} body {background-color: #ffffff; color: #000000; font-family:-apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, "Helvetica Neue",Arial, sans-serif; font-size: 16px; line-height: 1.7em;-webkit-font-smoothing: antialiased;} h1 { text-align: center; font-weight:700; margin: 16px 0; font-size: 32px; color:#000000; line-height: 1.25;} p {font-size: 20px; font-weight: 400; margin: 8px 0;} p, .attribution, {text-align: center;} #spinner {margin: 0 auto 30px auto; display: block;} .attribution {margin-top: 32px;} @keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} } @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} } #cf-bubbles > .bubbles { animation: fader 1.6s infinite;} #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;} #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;} .bubbles { background-color: #f58220; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; } a { color: #2c7cb0; text-decoration: none; -moz-transition: color 0.15s ease; -o-transition: color 0.15s ease; -webkit-transition: color 0.15s ease; transition: color 0.15s ease; } a:hover{color: #f4a15d} .attribution{font-size: 16px; line-height: 1.5;} .ray_id{display: block; margin-top: 8px;} #cf-wrapper #challenge-form { padding-top:25px; padding-bottom:25px; } #cf-hcaptcha-container { text-align:center;} #cf-hcaptcha-container iframe { display: inline-block;} </style> <meta http-equiv="refresh" content="35"> <script type="text/javascript"> //<![CDATA[ (function(){ window._cf_chl_opt={ cvId: "2", cType: "non-interactive", cNounce: "78960", cRay: "6bcdeb0d8fec669b", cHash: "df5caa022a26140", cPMDTk: "hcNPbaMOGwWYH.SrbCvPlGNz74B_6qr3rOPrwlu7prQ-1639385146-0-gaNycGzNB1E", cFPWv: "b", cTTimeMs: "1000", cRq: { ru: "aHR0cHM6Ly93d3czLnlnZ3RvcnJlbnQucmUv", ra: "UHJvd2xhcnIvMC4xLjguMTIzMSAocmFzcGJpYW4gMTAp", rm: "R0VU", d: "T60jWOKBvHaL35dwtsaogoos+rN5gFvzLZJCgGnFSiud+ja7BIoPIIkceEKJbTErX/I4ukI3Eg0vFBQBnLJfeLkkiWAbEIeYWv4TBBwj6zxLeProqQJFRw3T27t+znDIlG03pmvd4TkG5OCGRcc1VnunVnoZAmA/dG8cnBKjmS7fwemWsVZ7tCM83JXFM3lK1f/lWPQPVmNfDgintRIay99GfbOjY+PQBRpVN8t2NHx4mmfqN5wfgTYIS9gntsq5QMcIBTgWJP8Gj3Sm/dBbBuRLlcCaT+mVNbThSbOnSDW1oy4aZkRJWM+nFMhBeXiFmcklXJacX+kXuDMZZOJ65gOy5SFoHEJz3VjJc2potBjxCVnkkA1jUFNP05R8xc8FE4feiyZLzxo1350eFdbS9b8qY0v0stpbLT5ciFocRNEdT4C7C31M7CmUqdkfqGNz9iBpeTrIUGAQQw4zcFrG0KIQKgM9k0ahGuf/EwVA8s8V40SkthJ2OaTtFq8VJfACVwy4Ks/6iGKwm/hN5UeIPhj+Lb+U/f3YhXPyR1AQVmn39wAkwA8bPdHlYx7MevY5", t: "MTYzOTM4NTE0Ni40OTEwMDA=", m: "3chsKVX1FpbTswTm/q2YplHlgob8r1WxJnq//5X6MIw=", i1: "oQvB++CYBUGOacqiCV0JsA==", i2: "TWrklMN2fy04U5ICopaWgA==", zh: "7/0uRcIrMHtJnO7bYxG8RFoI3dHVYU5cWv92gqMp8q4=", uh: "Y9k1FFjG8sXX/QrssxG4omXPPshuFEcURnvUIAvkcfU=", hh: "aR58189KpyyWZ6MHb5IGEIRbbjm6kiCB/yMhtIBeqr8=", } } window._cf_chl_enter = function(){window._cf_chl_opt.p=1}; })(); //]]> </script> </head> <body> <table width="100%" height="100%" cellpadding="20"> <tr> <td align="center" valign="middle"> <div class="cf-browser-verification cf-im-under-attack"> <noscript> <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1> </noscript> <div id=(removed) style="display:none"> <div style="position: absolute; top: -250px; left: -250px;"><a href="https://preshweb.com/prize.php?b=4">table</a></div> <div id=(removed) <div class="bubbles"></div> <div class="bubbles"></div> <div class="bubbles"></div> </div> <h1><span data-translate="checking_browser">Checking your browser before accessing</span> www3.yggtorrent.re.</h1> <div id=(removed) class="cookie-warning" data-translate="turn_on_cookies" style="display:none"> <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p> </div> <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p> <p data-translate="allow_5_secs" id=(removed) >Please allow up to 5 seconds&hellip;</p> <p data-translate="redirecting" id=(removed) style="display:none">Redirecting&hellip;</p> </div> <form class="challenge-form" id=(removed) action="/?__cf_chl_f_tk=hcNPbaMOGwWYH.SrbCvPlGNz74B_6qr3rOPrwlu7prQ-1639385146-0-gaNycGzNB1E" method="POST" enctype="application/x-www-form-urlencoded"> <input type="hidden" name="md" value="Fe83mXGwheC8TJc5nNynjq7Ukqnj6Is.3jaaqby7.J0-1639385146-0-AQLXFl2S0M7Qdt3e2KLIFhSzdImiJJqvBRAvVfdwKltDD_7w4Vh3LhgKSbpMoyh_bXPyeLrL74-mqK39dJEv5fr2baedTJgBTWx9TsSlDB6Ff_F_12-B_KjlR_kHohL2vCEq-no2ED3Eo4q3rdvr4bBMAWqM0KxU16Kpag6NC3XNUeTEDYqjuIDxlchYOXcw54S_Ntp_MC-0kBFCrlQx2GG0h4H7oEU6tisOaUsbR4BIHPZpu-pT-t1dzsmRjw--kYILd9e_SD_wJfTZyVQHTF4I0qIpQzepoekpUck38eVEE2p9rp44Sd6pvrpdslhxD2ft-5IcQKMfwH2wBunEOHFIT31n2dMLyBXmFCYFqBLCegNDzb946pRmzXyX75wRopqb7dEflz5Xp4pjV8N00HE2n0TXF_q0JjV7MICV6DoEMDCqPohqjUXdPzOKNhOP-DhHfRVzC3Z2RPmws0TWJjPKvOt3vCwlvxyZECdOK75grIkUDxshiyZkkm9P8nlnIXqPSo0-ejke5GTTTpyshOYPf6YVVcIbb9wMaiwb476w8Tgqaq4aXM-EOWBlUQFkdMCm6eqlFh9o-LKqJIfP-ca33RQ7A8czNWM4K6lieKEQdPN0vlEPSuB9Kx0ec0l0RQ" /> <input type="hidden" name="r" value="GksHO78nuO3qQmrJWRSfcdmnItGkUKQaBc_ZVkYtVsg-1639385146-0-AVzugHutpGMzKDK91AK9uxDAobguodlIA1KY4h+75OR3SgtGol2vuRXTa3XOg9tBxnkv9XlQmEklFELyCHmP9bLaWSn5ofkQufTr6tQFHhG7OZaUif6sigw4ygqA8nknjnB2Y4XXs1N6inrs5w/+8ay9Act9GgB1cRBEkLZd4LSWymWz+ZFeAEbUmMBB6qzbMVRZEq6fRUvb8ew0cw/FyVNmnOX2X+OnGADTJtjFF7hDFyUUOCQ6jYym+ODzBIvEaD1CGMXm+uki38iMmaSCinHwEH6T+/btbZgvGWU517OGaej9LuYc2z5I/fa06YEDebHmJxdcsbLYRCtON1nsr6jJdGXJQOiYoxazwl9bIVlT7SAchdRIVjmhi6FARL+iEMa9i1jAGhnXJyz6+ooBa59nQB7dkmKb2DykRaskY/GP/bzrzppzm2NqlKVvcrg63Wl6arhiDnSXzoJhSY2SxoXwdRyAILUke6cWhehNRP84Sl7h+fuQKMTaYe/5dp0ZFXqeYL733K0vha+lZRLaBpKTEAhgfs9pKopEbodHGNLFBW/EMpI1nLirZx1AEZnD+CrSB6gEsvDoV1R2e6gXi8WWhYU1jY0pTdT/uEfbEaj50MbKObHCOgSKKxS+riVPE3yeLDb6vRMaZvZ73ZGgDcgVK1qDt0Gj248wWhYkVmaeDM6fWjISuVtxACugcJO0+8Ru9AfxD2mTHyMCtzTU0C/FysMwRjNfs0XTyUq1ht8WpTeY+3Wy8AoUsVSaOVwCyLZl3yV3mmvt4qs1it33mgYFR5zO0jx/dv3ISF09e3PoukUiP/dxg2s10gv96XUNP0fhaERa73k5xCwk7/BEmK7e57hTLqkxblqxXCSO5o41DcQTKgHzY1lPyRtdRqaB+4ExB7TsvjOksRUctpsqerfkTyKaRk6hjTI/GSmSH0gP7GYeG2cH/wlfJN28huApfJYqWktqv1vBNZ5h2Dp+fYhgSwJQmukRCC1u/6DGl3y5Ui/ta2rnOh5ilmRHRYv/lCtYOJam4BGEmPNJxyxzLL2eL+JSwXy0hwjKSP4+yfZC4Jz8G/nnXl16PSArzDkFjAUyLscHnmBi8JChl2mSnq7Xa+/VpJt97X9X08Uao2zEkHwwCT8baHYf1k26ljNv+N1wniCJfMnYvjvlQiT63viI3+1O3jg4IqEL4guL9Omtcg0y6r11FpJu8sHnFYByvHxAxYiNhDK5toTBpVq3bEoczXvONBI6u/CVXo1mV6WvsF5VYCVdYQrpHbQhbVCOjBZRoHSV4N+OICZFXdJmrSIVKrOZtK4mAuPlHmbfQSZwkMHInUw5MaBBO8TRlxXrcbSX877lP8NlI/PlAboAamHdhgSmlxg6zNCnt6zFB/THxp5dipX6Smtv6P+8HCqwQYwZ11ZSJkp1AC4bRvZOw4AffQDZpRHPsEme8cDPYrcpfUcVziXbx4xrzU+jOYmtRwT/NsFmV/hLtGauK0otgtdV4fnuodsMQm57a8954uPPArxSfwJCKkEJZ038beLORQx0bZPs2iTVjjGB9Qyx+GHrkeveze+oSv6Xf0I8Y8h7BK8LoLdwHZZNEoEQfsBN7aanPhBbJJ/VC6VD7epzSVQ2xfdXAKi8mvovZuTQ469+5BVvasSYsEW0OfmLnknUyqQsIIXsOC5JOSBYvdAOcr2mQ7SJj8m3UdptefNcWhvljmzqFyqFQoRMezBGayLVoS26RH/hD9QwB9F8ITkaCciBBxOBqksf5Ti5+h9S9ivcbeMrOWJRW0JTZ4VE3G4Lo4s79WheBjUCh6HMZErkbkI="/> <input type="hidden" value="7a0943fd8ba7cc912f122132dea873aa" id=(removed) name="jschl_vc"/>  <input type="hidden" name="pass" value="1639385147.491-hHycgEK5jk"/> <input type="hidden" id=(removed) name="jschl_answer"/> </form> <script type="text/javascript"> //<![CDATA[ (function(){ var a = document.getElementById('cf-content'); a.style.display = 'block'; var isIE = /(MSIE\|Trident\/\|Edge\/)/i.test(window.navigator.userAgent); var trkjs = isIE ? new Image() : document.createElement('img'); trkjs.setAttribute("src", "/cdn-cgi/images/trace/jschal/js/transparent.gif?ray=6bcdeb0d8fec669b"); trkjs.id = "trk_jschal_js"; trkjs.setAttribute("alt", ""); document.body.appendChild(trkjs); var cpo=document.createElement('script'); cpo.type='text/javascript'; cpo.src="/cdn-cgi/challenge-platform/h/b/orchestrate/jsch/v1?ray=6bcdeb0d8fec669b"; if (window._cf_chl_opt.cPMDTk && window.history && window.history.replaceState && window.URLSearchParams) { var ogU = location.pathname + location.search; var p = new URLSearchParams(location.search); p.set('__cf_chl_rt_tk', window._cf_chl_opt.cPMDTk); history.replaceState(null, null, location.pathname + '?' + p.toString()); cpo.onload = function() { history.replaceState(null, null, ogU); }; } document.getElementsByTagName('head')[0].appendChild(cpo); }()); //]]> </script> <div id=(removed) style="background-image:url('/cdn-cgi/images/trace/jschal/nojs/transparent.gif?ray=6bcdeb0d8fec669b')"> </div> </div> <div class="attribution"> DDoS protection by <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a> <br /> <span class="ray_id">Ray ID: <code>6bcdeb0d8fec669b</code></span> </div> </td> </tr> </table> </body> </html> |  
  | 9:45am | Cardigann | Adding request: https://www3.yggtorrent.re/engine/search?category=all&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date

</body>
</html>

[AB#2136](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2136)

**Comment by bakerboy448** [comment] 2021-12-13 13:27
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/698

Duplicate of https://github.com/Prowlarr/Prowlarr/issues/709

**Comment by bakerboy448** [comment] 2021-12-13 13:27
- Events are not valid for bug reports
- YGG is confirmed to be working by others; FlareSolverr v2.1 is likely needed

Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

**Closed by bakerboy448** 2021-12-13 13:27 UTC
Labels: Type: Bug, Status: Needs Triage
