### ISSUE TITLE
Add mirrors for trackers banned in my country

### ISSUE THREAD

**Issue by SumitBajoria** [Prowlarr/Prowlarr#245] opened 2021-06-19 08:40 UTC
**Is your feature request related to a problem? Please describe.**
I am from India and due to the policies of our government, many torrent and downloading sites are banned by all ISPs. To get around this and to cater to their userbase from within the country, sites like bwtorrents use mirrors. However, it appears that when I add my credentials to prowlarr, it checks the main site and thus times out.

**Describe the solution you'd like**
Allow the user to select or specify the mirror to a particular tracker when adding it to prowlarr.

**Describe alternatives you've considered**
Jackett allows me to do this.

**Additional context**
Prowlarr looks promising. However, I can only adapt to it if the trackers I use are accessible.

**Comment by Qstick** [comment] 2021-06-19 11:38
Duplicate of #87 - In Progress

**Closed by Qstick** 2021-06-19 11:38 UTC
Labels: Type: Feature Request
