### ISSUE TITLE
Instance Specific Suffixes on Indexers

### ISSUE THREAD

**Issue by SiPurdy44** [Prowlarr/Prowlarr#1821] opened 2023-08-09 07:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have multiple instances of Prowlarr set up linked to shared Sonarr/Radarr instances.

With a large-ish number of indexers, it's difficult to differentiate between the 2. Being able to specify against the Prowlarr instance what the suffix should be and having that used against all of the indexers for that instance.

### Describe the solution you'd like

As part of the General settings, add the following options:

- Instance Name - Mandatory, default to "Prowlarr"
- Indexer Format, option choice, someway of giving options like "{indexer.name} ({instance})" (which is the current format) or "{instance} - {indexer.name}" for having the instance prefix the indexer name.

### Describe alternatives you've considered

Currently forced to use the name of the indexer, the problem is with Add and Remove Only, if the name isn't suffixed at that point it's difficult to correct.

### Anything else?

N/A

**Comment by SiPurdy44** [comment] 2023-08-10 07:26
Wasn't after adding more to the indexer names, suggestion was to have defaults configured to the current " (Prowlarr)" suffix, but have the ability to change what that suffix is, and where it's positioned in the indexer name.

Your comment about people complaining about the added suffix, my suggestion could be extended to allow for complete removal of the suffix if desired.

**Comment by Qstick** [comment] 2023-08-19 02:33
Isn't there already an issue open to customize this?

**Comment by bakerboy448** [comment] 2023-08-19 19:51
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/544

**Closed by bakerboy448** 2023-08-19 19:51 UTC
Labels: Type: Feature Request, Status: Needs Triage, Area: Indexer, Priority: Low
