### ISSUE TITLE
Flaresolverr not used if Indexer Reauth detected after Proxying Request

### ISSUE THREAD

**Issue by Bastien42** [Prowlarr/Prowlarr#660] opened 2021-12-01 20:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when testing YGGtorrent with flaresolverr because they use a cloudflare protection flaresolverr report that the challenge was solved but Prowlar
[prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/7636988/prowlarr.txt)
r 

### Expected Behavior

should report with no failure 

### Steps To Reproduce

add YGGtorrent and Flaresolverr then run a test shouldn't not report successfully 

### Environment

```markdown
- OS: windows 10 pro
- Prowlarr:0.1.5.1164
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: chrome Version 96.0.4664.45
```

### What branch are you running?

Develop

### Trace Logs?

https://gist.github.com/bakerboy448/66aca865141a9f0bc7870e15661b61d7

```
2021-12-01 22:28:21.8|Debug|FlareSolverr|Applying FlareSolverr Proxy FlareSolverr to request https://www3.yggtorrent.nz/engine/search?category=2145&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date
2021-12-01 22:28:21.8|Trace|HttpClient|Req: [POST] http://192.168.1.197:8191/v1
2021-12-01 22:28:21.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-12-01 22:28:28.2|Trace|HttpClient|Res: [POST] http://192.168.1.197:8191/v1: 200.OK (6409 ms)
2021-12-01 22:28:28.3|Trace|Cardigann|Attempting to re-auth based on indexer search response
2021-12-01 22:28:28.3|Trace|IndexerHttpClient|Req: [GET] https://www3.yggtorrent.nz/
2021-12-01 22:28:28.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-12-01 22:28:28.3|Trace|IndexerHttpClient|Res: [GET] https://www3.yggtorrent.nz/: 403.Forbidden
```

[AB#2022](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2022)

**Comment by bakerboy448** [comment] 2021-12-01 20:49
Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

Not convinced this is a bug; there's no call to flaresolverr being made; can re-open if needed

do YGG and the flaresolverr share the same tag? if not - that's likely the cause.

**Comment by Bastien42** [comment] 2021-12-01 20:58
yes same tag I've made sure behaviour is different when I disable / enable Indexer Proxies can post the two different log if you want

**Comment by Bastien42** [comment] 2021-12-01 20:59
![image](https://user-images.githubusercontent.com/37946663/144312961-487d6004-0a10-420d-adb6-5f7cb31d736d.png)

**Comment by Bastien42** [comment] 2021-12-01 21:01
[prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/7637057/prowlarr.txt)
without the indexer proxy

**Comment by Bastien42** [comment] 2021-12-01 21:02
[prowlarr.txt](https://github.com/Prowlarr/Prowlarr/files/7637065/prowlarr.txt)
with the indexer proxy

**Comment by Bastien42** [comment] 2021-12-01 21:07
here you can see the request in flaresolverr 

```
2021-12-01T21:06:31+00:00 INFO REQ-18 Incoming request => POST /v1 body: {"maxTimeout":60000,"cmd":"request.get","url":"https://www3.yggtorrent.nz/engine/search?category=2145&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"}

2021-12-01T21:06:31+00:00 WARN REQ-18 Request parameter 'userAgent' was removed in FlareSolverr v2.

2021-12-01T21:06:33+00:00 INFO REQ-18 Cloudflare detected

2021-12-01T21:06:37+00:00 INFO REQ-18 Challenge solved

```
2021-12-01T21:06:37+00:00 INFO REQ-18 Response in 58

**Comment by bakerboy448** [comment] 2021-12-01 21:34
Yup thats a bug @Qstick - seems related to the recent only use CF when CF is detected changes?

```
2021-12-01 22:28:21.8|Debug|FlareSolverr|Applying FlareSolverr Proxy FlareSolverr to request https://www3.yggtorrent.nz/engine/search?category=2145&name=&description=&file=&uploader=&sub_category=&do=search&order=desc&sort=publish_date
2021-12-01 22:28:21.8|Trace|HttpClient|Req: [POST] http://192.168.1.197:8191/v1
2021-12-01 22:28:21.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-12-01 22:28:28.2|Trace|HttpClient|Res: [POST] http://192.168.1.197:8191/v1: 200.OK (6409 ms)
2021-12-01 22:28:28.3|Trace|Cardigann|Attempting to re-auth based on indexer search response
2021-12-01 22:28:28.3|Trace|IndexerHttpClient|Req: [GET] https://www3.yggtorrent.nz/
2021-12-01 22:28:28.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-12-01 22:28:28.3|Trace|IndexerHttpClient|Res: [GET] https://www3.yggtorrent.nz/: 403.Forbidden
```

1. Indexer is queried
2. Indexer Responses with cloudflare
3. We then proxy the request
4. indexer responses indicates we need to reauth
5. we do not proxy the next request
6. we hit cloudflare
7. we fail

**Comment by Oenseb** [comment] 2021-12-01 23:55
same problem with yggtorrent

i tried falresolverr update, prowlarr works with flaresolver 1.2.9 max 2.x.x seems not compatible

**Comment by bakerboy448** [comment] 2021-12-02 00:38
> i tried falresolverr update, prowlarr works with flaresolver 1.2.9 max 2.x.x seems not compatible

You're out of date; upgrade.  Prowlarr is compatible with FS v2+

**Comment by Qstick** [comment] 2021-12-02 03:53
Should be fixed on latest nightly to at least get results, though something still seems quite slow. I'll have to dig into that later.

**Comment by Bastien42** [comment] 2021-12-02 09:17
@Qstick can confirm it works kind off extremely slow seems to be on prowlarr as flaresolverr complete the challenge quite fast around 10sec though wasn't not able to find results in sonarr or radarr yet it would always timeout before but in prowlarr it work after a good minutes

**Comment by bakerboy448** [comment] 2021-12-02 22:12
Reopening as there's still issues around this

https://gist.github.com/bakerboy448/ff91f980a61cb8ca185f27f3a4c76aa0

https://discord.com/channels/767843854736949299/767843854824374281/916088248974065705

**Comment by bakerboy448** [comment] 2021-12-04 18:08
https://gist.githubusercontent.com/bakerboy448/2150cfe177e281b3474be069f9e18550/raw/65bf5709c2543c99530aac832d8af9cd887d3760/yggcookie-noua.yml

Use this custom YGG Cookie definition + Flaresolverr should get YGG working for now
The only catch is if Flaresolverr fails to get the response within 60s Flaresolverr will timeout and Prowlarr will fail.

I have a PR up to remove the UserAgent from the CookieDefinition (for now...tho I also question if it is even needed)  so once that gets merged you can switch back to the standard built in cookie definition

-----
It goes without saying the non-cookie definition that uses the login method is not exactly working currently.  Seems primarily due to the process below losing the ygg auth cookie or possibly never actually logining once passed FS:

search attempt => CF detected => Proxy via FS => FS responds => login if needed checked => login is needed => Prowlarr hits flaresolverr again and dies.

**Comment by Bastien42** [comment] 2021-12-04 19:13
so yes your temp fix works i think it is the same that the guys at jackett use but now we have another issue is that flaresolverr now is using an user agent that is banned by the CF of YGG 

https://github.com/FlareSolverr/FlareSolverr/issues/234

**Comment by bakerboy448** [comment] 2021-12-04 19:25
Almost seems like the YGG folks are like Nyaa Devs and hate automation. thus intentionally making automation as hard as possible and think RSS feeds are all anyone needs.

**Comment by Bastien42** [comment] 2021-12-04 19:32
yeah i've had so many talk in the past before flaresolverr was a thing we've had the jackett dev fight CF tricks to work past it and the mention of an API or even whitelisting us is most likely gonna be a no and you're right RSS are basically useless they have a whole RSS category https://www3.yggtorrent.nz/rss and now it's all render useless for everyone even the common user loading it into a torrent app weird they enable CF when they get DDOS attack which understandable but people that automate DL and seed right after are basically insuring the longevity of every torrents weird move

**Closed** 2021-12-06 00:01 UTC
Labels: Type: Bug, Area: Indexers, Area: Proxy
