### ISSUE TITLE
Filtering options

### ISSUE THREAD

**Issue by 4C3T** [Prowlarr/Prowlarr#257] opened 2021-06-21 23:14 UTC
**Is your feature request related to a problem? Please describe.**
<I find it very cumbersome to add new indexers. First off, I know this is a beta, and it's bound for greatness - I Love it! But having to scroll page-wise just to find the next one in the list (It doesn't exclude previously added ones - Jackett does this when adding!), and accidentally picking the wrong one means you'll have to begin all over again.>

**Describe the solution you'd like**
<I'd like to see either a page in settings where you can choose to hide certain supported languages from indexers, preferably with check-boxes, or a multi-search-filter (stored, like those in Radarr/Sonarr) to always filter out private/public, and certain languages>

**Describe alternatives you've considered**
<Nothing to consider>

**Additional context**
<Nope>

**Comment by bakerboy448** [comment] 2021-06-21 23:22
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/233

**Closed by bakerboy448** 2021-06-21 23:22 UTC
Labels: Type: Feature Request
