### ISSUE TITLE
0 minutes torrent from different indexers

### ISSUE THREAD

**Issue by Bazzu85** [Prowlarr/Prowlarr#661] opened 2021-12-02 14:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Already posted on discord prowlarr support
Searching from radarr/sonarr/prowlarr some torrents are showed with bad ages

check this screens:
https://imgur.com/a/gcT994S

### Expected Behavior

The age as on jackett

### Steps To Reproduce

Search for example "king kong extended ac3 5 1" on 1337x and kickasstorrents

![image](https://user-images.githubusercontent.com/7345587/144444847-1c1880df-acbc-425b-8731-0209472f4c3d.png)

this is not a single indexer problem IMHO

### Environment

```markdown
- OS: Windows 10 PRO
- Prowlarr: 0.1.5.1164
- Docker Install: NO
- Using Reverse Proxy: NO
- Browser: Chrome
```

### What branch are you running?

Develop

### Trace Logs?

easily reproducible

[AB#2025](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2025)

**Comment by bakerboy448** [comment] 2021-12-02 15:33
Closing; Cannot reproduce on my dev instance based on commit https://github.com/Prowlarr/Prowlarr/commit/c83c8183808b225eda8f1292eafa40643bcc99a0

![image](https://user-images.githubusercontent.com/55419169/144452207-9d88f12b-3984-4471-8939-163ac94c9a81.png)

The two releases with no seeders are confirmed to have none on the site.

Both Indexers are known to be some of the worst public trackers that exist and are extremely flakey (and lie about their seeds), so it seems like it's flukes caused by the crappy indexer sites?

**Closed by bakerboy448** 2021-12-02 15:33 UTC
Labels: Type: Bug, Status: Needs Triage

**Comment by Bazzu85** [comment] 2021-12-04 18:11
Sorry but I have to reopen it...

using last dev release:
![image](https://user-images.githubusercontent.com/7345587/144720066-4bc0ab24-eea0-4cad-a566-12c0a0a293c7.png)
![image](https://user-images.githubusercontent.com/7345587/144720060-b993cb89-6857-411f-8f71-abfb81b70aea.png)


and searching for example "Squid game" here's some problematic results:
![image](https://user-images.githubusercontent.com/7345587/144720056-378d8fb7-6fd6-4931-97cd-2451d1f244d1.png)

**Comment by bakerboy448** [comment] 2021-12-04 18:13
Just tested; cannot reproduce
- 23 releases from 1337x for `Squid Game` for `TV` Category
all releases have dates as expected

![image](https://user-images.githubusercontent.com/55419169/144720133-8c4a25db-7762-4a97-a14e-508633a5490b.png)

**Comment by Bazzu85** [comment] 2021-12-04 18:25
Same search and filters..
I have this:

![image](https://user-images.githubusercontent.com/7345587/144720454-6aea822b-d6b2-4446-822f-84f19eaf328f.png)

how can we debug it?

**Comment by Bazzu85** [comment] 2021-12-04 18:26
trying the term "Squid Game Season 1 Complete 2021 1080p HD Dual Audio with Subtitles" what do you have?

**Comment by bakerboy448** [comment] 2021-12-04 18:55
![image](https://user-images.githubusercontent.com/55419169/144720551-ac3f2a44-df04-4fb8-acee-76d7ed87d2d3.png)

Swing by discord
Check the Trace w/ Indexer Response ([Wiki has details](https://wiki.servarr.com/prowlarr/troubleshooting));  Do your timestamps match mine?

[Trace w/ Response](https://gist.github.com/bakerboy448/dc60b6b2efed1d3886ee0755d806977d)

keywords are `coll-date` for 1337x and a little bit after `Posted by` for KAT

Excerpts:

1337x - Reports Oct 5th '21 (~2 months)
```
<td class="coll-2 seeds">1604</td>
<td class="coll-3 leeches">1014</td>
<td class="coll-date">Oct. 5th '21</td>
<td class="coll-4 size mob-uploader">5.4 GB<span class="seeds">1604</span></td>
<td class="coll-5 uploader"><a href="/user/VARIOUS/">VARIOUS</a></td>
```


KAT - Reports 1 Month
```
<span class="font11px lightgrey block">
Posted by
<i title="Verified Uploader" class="ka ka-verify" style="font-size: 16px;color:orange;">
</i>
<a class="plain" href="/user/VARIOUS/">
VARIOUS </a>
in
<span>
<strong>
<a href="/tv/">
TV </a> &gt;
<a href="/tv/hd/">
HD </a>
</strong>
</span>
</span>
</div>
</div>
</td>
<td class="nobr center">
5.4 GB </td>
<td class="center">
VARIOUS </td>
<td class="center" title="1<br/>month">
1<br />month </td>
<td class="green center">
678 </td>
<td class="red lasttd center">
816 </td>
</tr> </tbody>
```

**Comment by Bazzu85** [comment] 2021-12-09 17:08
I tried different search and didn't found that keyword.

can we try another way?
here's an example
![image](https://user-images.githubusercontent.com/7345587/145442674-62f0fc74-f27d-4171-ab41-307f5f38fdbd.png)
keyword: Squid Game S01 1080p WEB AAC 6CH x265-LUMI
here's the trace: https://gist.github.com/Bazzu85/3834d16b48a52e82ec0f2fffb058e612

can be usefull?

**Comment by Bazzu85** [comment] 2021-12-12 14:08
additionally, for a release when happens and re-trying after few hours the problem vanish..
