### ISSUE TITLE
Dropping already used indexers from the add indexer list

### ISSUE THREAD

**Issue by ArthurMitchell42** [Prowlarr/Prowlarr#309] opened 2021-07-01 22:23 UTC
**Is your feature request related to a problem? Please describe.**

It would be nice if when you select add an indexer the list offered excluded indexers that have already been selsected

**Describe the solution you'd like**

When selecting indexers-> Add indexer the list presented could have indexers already present in the configuration either excluded or greyed out/marked in some way. This would make it far quicker to find newly available or unused indexers.

**Describe alternatives you've considered**

**Additional context**

[AB#1165](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1165)

**Comment by bakerboy448** [comment] 2021-07-01 22:24
Duplicate of #https://github.com/Prowlarr/Prowlarr/issues/233

**Closed by bakerboy448** 2021-07-01 22:24 UTC
Labels: Type: Feature Request
