### ISSUE TITLE
[FEAT] Choose download directory path before downloading

### ISSUE THREAD

**Issue by almottier** [Prowlarr/Prowlarr#719] opened 2021-12-18 10:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

I would like to have the ability to choose the directory download path before adding a torrent to my download client (transmission) from Prowlarr.
I am using Plex and I have a directory for Movies, an other one for TV Shows. I would like to choose the directory (or the download client) every time I start a download.

### Describe alternatives you've considered

I am using two download clients in Prowlarr, they have the same configuration, only the download directory path differs. I enable/disable one of them before adding a download to grab the release in the expected directory.

### Anything else?

No

[AB#2196](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2196)

**Comment by bakerboy448** [comment] 2021-12-18 14:23
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/170

**Closed by bakerboy448** 2021-12-18 14:23 UTC
Labels: Type: Feature Request, Status: Needs Triage
