### ISSUE TITLE
Cannot sync indexers to Lazylibrarian 

### ISSUE THREAD

**Issue by skuizy** [Prowlarr/Prowlarr#675] opened 2021-12-06 21:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When syncing indexers to LL an error occurs and indexers don't get added.

### Expected Behavior

Indexers getting added to LL.

### Environment

```markdown
- OS: Ubuntu 20.04.3 LTS
- Linux odroid 5.4.156+ #1 SMP PREEMPT Sun Nov 7 23:31:32 CET 2021 armv7l armv7l armv7l GNU/Linux
- Prowlarr: 0.1.7.1199
- Docker Install: no
```

### What branch are you running?

Develop

### Trace Logs?

```2021-12-06 22:31:58.7|Error|ApplicationService|An error occurred while talking to remote application.

[v0.1.7.1199] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Applications.LazyLibrarian.LazyLibrarianV1Proxy.GetIndexers(LazyLibrarianSettings settings) in D:\a\1\s\src\NzbDrone.Core\Applications\LazyLibrarian\LazyLibrarianV1Proxy.cs:line 46
   at NzbDrone.Core.Applications.LazyLibrarian.LazyLibrarian.GetIndexerMappings() in D:\a\1\s\src\NzbDrone.Core\Applications\LazyLibrarian\LazyLibrarian.cs:line 47
   at NzbDrone.Core.Applications.ApplicationService.<>c.<SyncIndexers>b__13_0(IApplication a) in D:\a\1\s\src\NzbDrone.Core\Applications\ApplicationService.cs:line 115
   at NzbDrone.Core.Applications.ApplicationService.ExecuteAction[TResult](Func`2 applicationAction, IApplication application) in D:\a\1\s\src\NzbDrone.Core\Applications\ApplicationService.cs:line 236
```

```
curl -L http://10.200.1.1:5299/lazylibrarian/api\?cmd\=listProviders\&apikey\=removed
{"newznab": [{"NAME": "Newznab0", "DISPNAME": "Newznab0", "ENABLED": false, "HOST": "", "API": "", "GENERALSEARCH": "search", "BOOKSEARCH": "book", "MAGSEARCH": "", "AUDIOSEARCH": "", "COMICSEARCH": "", "BOOKCAT": "7000,7020", "MAGCAT": "7010", "AUDIOCAT": "3030", "COMICCAT": "7030", "EXTENDED": "1", "UPDATED": "", "MANUAL": false, "APILIMIT": 0, "APICOUNT": 0, "RATELIMIT": 0, "DLPRIORITY": 0, "DLTYPES": "A,C,E,M"}], "torznab": [{"NAME": "Torznab0", "DISPNAME": "Torznab0", "ENABLED": false, "HOST": "", "API": "", "GENERALSEARCH": "search", "BOOKSEARCH": "book", "MAGSEARCH": "", "AUDIOSEARCH": "", "COMICSEARCH": "", "BOOKCAT": "8000,8010", "MAGCAT": "8030", "AUDIOCAT": "3030", "COMICCAT": "8020", "EXTENDED": "1", "UPDATED": "", "MANUAL": false, "APILIMIT": 0, "APICOUNT": 0, "RATELIMIT": 0, "DLPRIORITY": 0, "DLTYPES": "A,C,E,M", "SEEDERS": 0}], "rss": [{"NAME": "RSS_0", "DISPNAME": "RSS_0", "ENABLED": false, "HOST": "", "DLPRIORITY": 0, "DLTYPES": "E"}], "irc": [{"NAME": "IRC_0", "DISPNAME": "IRC_0", "ENABLED": false, "SERVER": "", "CHANNEL": "", "BOTNICK": "", "BOTPASS": "", "DLPRIORITY": 0, "DLTYPES": "E"}], "torrent": [{"ENABLED": false, "KAT_HOST": "kickass.cd", "KAT_DLPRIORITY": 0, "KAT_DLTYPES": "A,E,M", "KAT_SEEDERS": 1, "NAME": "KAT"}, {"ENABLED": false, "WWT_HOST": "https://worldwidetorrents.me", "WWT_DLPRIORITY": 0, "WWT_DLTYPES": "A,E,M", "WWT_SEEDERS": 1, "NAME": "WWT"}, {"ENABLED": false, "TPB_HOST": "https://pirateproxy.cc", "TPB_DLPRIORITY": 0, "TPB_DLTYPES": "A,C,E,M", "TPB_SEEDERS": 1, "NAME": "TPB"}, {"ENABLED": false, "ZOO_HOST": "https://zooqle.com", "ZOO_DLPRIORITY": 0, "ZOO_DLTYPES": "A,E,M", "ZOO_SEEDERS": 1, "NAME": "ZOO"}, {"ENABLED": false, "LIME_HOST": "https://www.limetorrents.cc", "LIME_DLPRIORITY": 0, "LIME_DLTYPES": "A,E,M", "LIME_SEEDERS": 1, "NAME": "LIME"}, {"ENABLED": false, "TDL_HOST": "torrentdownloads.me", "TDL_DLPRIORITY": 0, "TDL_DLTYPES": "A,E,M", "TDL_SEEDERS": 1, "NAME": "TDL"}, {"ENABLED": false, "TRF_HOST": "torrof.com", "TRF_DLPRIORITY": 0, "TRF_DLTYPES": "A,E,M", "TRF_SEEDERS": 1, "NAME": "TRF"}], "direct": [{"ENABLED": false, "BOK_HOST": "b-ok.cc", "BOK_DLPRIORITY": 0, "BOK_DLTYPES": "E", "BOK_DLLIMIT": 5}, {"ENABLED": false, "BFI_HOST": "en.bookfi.net", "BFI_DLPRIORITY": 0, "BFI_DLTYPES": "E"}, {"NAME": "GEN_0", "DISPNAME": "GEN_0", "ENABLED": false, "HOST": "gen.lib.rus.ec", "SEARCH": "foreignfiction/index.php", "DLPRIORITY": 0, "DLTYPES": "E,M"}, {"NAME": "GEN_1", "DISPNAME": "GEN_1", "ENABLED": false, "HOST": "", "SEARCH": "", "DLPRIORITY": 0, "DLTYPES": "E"}]}%
```

[AB#2090](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2090)

**Comment by bakerboy448** [comment] 2021-12-06 21:52
@philborman can you take a look?

**Comment by Qstick** [comment] 2021-12-06 22:25
Appears the API responses are nowhere near Mylar, so this is going to take some more time. Thanks for reporting @skuizy

**Comment by philborman** [comment] 2021-12-06 22:25
Seems the version of LazyLibrarianV1Proxy.cs that was merged is an older one, not the most recent upload. The names of some lazylibrarian api calls are incorrect. Line 34 "getVersion" should be "getCurrentVersion" and line 40 "listProviders" should be "listNabProviders"  

The version uploaded on 18th August is correct, commit  Lazylibrarian integration #469 
but the merge yesterday says

 Closed with unmerged commits

This pull request is closed, but the philborman:master branch has unmerged commits. You can delete this branch if you wish.

**Comment by bakerboy448** [comment] 2021-12-06 22:32
Guessing things got crossed up in the various PRs?
Should be an easy quick PR to patch in the new/correct file then, no?

**Comment by Qstick** [comment] 2021-12-06 22:33
`getVersion` should be fine per API Docs?

https://lazylibrarian.gitlab.io/api/#getversion

**Comment by philborman** [comment] 2021-12-06 22:38
getCurrentVersion returns mylar compatible response, get Version returns more info

**Comment by philborman** [comment] 2021-12-06 22:41
getNabProviders only returns torznab/newznab
getProviders also returns torrent/irc/rss etc

**Comment by Qstick** [comment] 2021-12-07 02:41
What happens on latest?

**Comment by bakerboy448** [comment] 2021-12-10 00:07
for posterity:
Hopefully fixed by https://github.com/Prowlarr/Prowlarr/commit/d2cf060473e11f04b9d1debeac48923b925064a9 in `0.1.7.1209`

**Comment by skuizy** [comment] 2021-12-18 18:31
Hello,

Thanks for the update, indexers sync now ! 
Names are empty in LL tho so it's a bit hard to configure trackers and keep track of downloads. I'll post a log of sync to try to sort that.

**Comment by skuizy** [comment] 2021-12-18 18:59
Prowlarr logs : 
```
1-12-18 19:53:13.0|Trace|Http|Req: 32 [POST] /prowlarr/api/v1/command (from 10.200.1.1)
2021-12-18 19:53:13.0|Trace|CommandQueueManager|Publishing ApplicationIndexerSync
2021-12-18 19:53:13.0|Trace|CommandQueueManager|Checking if command is queued or started: ApplicationIndexerSync
2021-12-18 19:53:13.0|Trace|CommandQueueManager|Inserting new command: ApplicationIndexerSync
2021-12-18 19:53:13.0|Trace|CommandExecutor|ApplicationIndexerSyncCommand -> ApplicationService
2021-12-18 19:53:13.0|Trace|CommandQueueManager|Marking command as started: ApplicationIndexerSync
2021-12-18 19:53:13.0|Trace|Http|Res: 32 [POST] /prowlarr/api/v1/command: 201.Created (41 ms)
2021-12-18 19:53:13.1|Trace|EventAggregator|Publishing CommandUpdatedEvent
2021-12-18 19:53:13.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandController
2021-12-18 19:53:13.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandController
2021-12-18 19:53:13.2|Debug|ApplicationFactory|Temporarily ignoring application Lidarr till 18/12/2021 22:38:26 due to recent failures.
2021-12-18 19:53:13.2|Debug|ApplicationFactory|Temporarily ignoring application Radarr till 18/12/2021 22:38:26 due to recent failures.
2021-12-18 19:53:13.2|Debug|ApplicationFactory|Temporarily ignoring application Sonarr till 18/12/2021 22:38:26 due to recent failures.
2021-12-18 19:53:13.2|Debug|IndexerFactory|Temporarily ignoring indexer Idope till 19/12/2021 19:36:05 due to recent failures.
2021-12-18 19:53:13.2|Debug|IndexerFactory|Temporarily ignoring indexer Fou-Du-Cinema till 19/12/2021 15:12:41 due to recent failures.
2021-12-18 19:53:13.2|Debug|IndexerFactory|Temporarily ignoring indexer P2PElite till 19/12/2021 19:37:12 due to recent failures.
2021-12-18 19:53:13.3|Debug|IndexerFactory|Temporarily ignoring indexer ScenePalace till 19/12/2021 19:37:17 due to recent failures.
2021-12-18 19:53:13.3|Debug|IndexerFactory|Temporarily ignoring indexer Torrent9 till 19/12/2021 19:36:07 due to recent failures.
2021-12-18 19:53:13.3|Debug|IndexerFactory|Temporarily ignoring indexer Torrentz2eu till 19/12/2021 19:34:59 due to recent failures.
2021-12-18 19:53:13.3|Debug|IndexerFactory|Temporarily ignoring indexer YGGtorrent till 19/12/2021 19:35:00 due to recent failures.
2021-12-18 19:53:13.3|Debug|IndexerFactory|Temporarily ignoring indexer 01Torrent till 19/12/2021 19:36:08 due to recent failures.
2021-12-18 19:53:13.3|Debug|IndexerFactory|Temporarily ignoring indexer CRT2FA till 19/12/2021 19:36:11 due to recent failures.
2021-12-18 19:53:13.3|Trace|HttpClient|Req: [GET] http://10.200.1.1:5299/lazylibrarian/api?cmd=listNabProviders&apikey=(removed)
2021-12-18 19:53:13.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-12-18 19:53:13.3|Trace|HttpClient|Res: [GET] http://10.200.1.1:5299/lazylibrarian/api?cmd=listNabProviders&apikey=(removed) 200.OK (12 ms)
2021-12-18 19:53:13.3|Debug|LazyLibrarian|Updating indexer 1337x [1]
2021-12-18 19:53:13.3|Trace|HttpClient|Req: [GET] http://10.200.1.1:5299/lazylibrarian/api?cmd=listNabProviders&apikey=(removed)
2021-12-18 19:53:13.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-12-18 19:53:13.3|Trace|HttpClient|Res: [GET] http://10.200.1.1:5299/lazylibrarian/api?cmd=listNabProviders&apikey=(removed) 200.OK (11 ms)
2021-12-18 19:53:13.4|Debug|LazyLibrarian|Remote indexer not found, re-adding 1337x to LazyLibrarian
2021-12-18 19:53:13.4|Trace|HttpClient|Req: [GET] http://10.200.1.1:5299/lazylibrarian/api?cmd=addProvider&apikey=(removed)&name=1337x%20%28Prowlarr%29&providertype=torznab&host=http%3A%2F%2F10.200.1.2%3A9696%2Fprowlarr%2F1%2Fapi&prov_apikey=(removed)&enabled=true&categories=5000%2C3000%2C2000%2C4000%2C1000%2C6000%2C0%2C7000
2021-12-18 19:53:13.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-12-18 19:53:15.9|Trace|HttpClient|Res: [GET] http://10.200.1.1:5299/lazylibrarian/api?cmd=addProvider&apikey=(removed)&name=1337x%20%28Prowlarr%29&providertype=torznab&host=http%3A%2F%2F10.200.1.2%3A9696%2Fprowlarr%2F1%2Fapi&prov_apikey=(removed)&enabled=true&categories=5000%2C3000%2C2000%2C4000%2C1000%2C6000%2C0%2C7000: 200.OK (2572 ms)
2021-12-18 19:53:16.0|Debug|LazyLibrarian|Updating indexer Abnormal [2]
2021-12-18 19:53:16.0|Trace|HttpClient|Req: [GET] http://10.200.1.1:5299/lazylibrarian/api?cmd=listNabProviders&apikey=(removed)
2021-12-18 19:53:16.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-12-18 19:53:16.0|Trace|HttpClient|Res: [GET] http://10.200.1.1:5299/lazylibrarian/api?cmd=listNabProviders&apikey=(removed) 200.OK (11 ms)
2021-12-18 19:53:16.0|Debug|LazyLibrarian|Remote indexer not found, re-adding Abnormal to LazyLibrarian
2021-12-18 19:53:16.0|Trace|HttpClient|Req: [GET] http://10.200.1.1:5299/lazylibrarian/api?cmd=addProvider&apikey=(removed)&name=Abnormal%20%28Prowlarr%29&providertype=torznab&host=http%3A%2F%2F10.200.1.2%3A9696%2Fprowlarr%2F2%2Fapi&prov_apikey=(removed)&enabled=true&categories=5000%2C2000%2C4000%2C7000
2021-12-18 19:53:16.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-12-18 19:53:18.6|Trace|HttpClient|Res: [GET] http://10.200.1.1:5299/lazylibrarian/api?cmd=addProvider&apikey=(removed)&name=Abnormal%20%28Prowlarr%29&providertype=torznab&host=http%3A%2F%2F10.200.1.2%3A9696%2Fprowlarr%2F2%2Fapi&prov_apikey=(removed)&enabled=true&categories=5000%2C2000%2C4000%2C7000: 200.OK (2575 ms)
```

LL logs :
```
18-déc.-2021 19:53:13 - DEBUG   :: API : api.py:fetch_data:285 : Received API command from 10.200.1.2: listNabProviders {}
18-déc.-2021 19:53:13 - DEBUG   :: API : api.py:fetch_data:285 : Received API command from 10.200.1.2: listNabProviders {}
18-déc.-2021 19:53:13 - DEBUG   :: API : api.py:fetch_data:285 : Received API command from 10.200.1.2: addProvider {'name': '1337x (Prowlarr)', 'providertype': 'torznab', 'host': 'http://10.200.1.2:9696/prowlarr/1/api', 'prov_apikey'
: '57940d159ac44c6880da5f14b9e85939', 'enabled': 'true', 'categories': '5000,3000,2000,4000,1000,6000,0,7000'}
18-déc.-2021 19:53:13 - INFO    :: API : __init__.py:config_write:1245 : Writing config for section [Torznab]
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving OL_URL unchanged (https://www.openlibrary.org)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving GR_URL unchanged (https://www.goodreads.com)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving GB_URL unchanged (https://www.googleapis.com)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving LT_URL unchanged (https://www.librarything.com)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving CV_URL unchanged (https://www.comicvine.gamespot.com)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving CX_URL unchanged (https://www.comixology.com)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving USER_ACCOUNTS unchanged (1)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving SINGLE_USER unchanged (0)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving ADMIN_EMAIL unchanged ()
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving SYS_ENCODING unchanged ()
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving HOMEPAGE unchanged (eBooks)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving LOGDIR unchanged (/var/log/LazyLibrarian)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving LOGLIMIT unchanged (500)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving LOGFILES unchanged (10)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving LOGSIZE unchanged (20480000)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving LOGREDACT unchanged (0)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving HOSTREDACT unchanged (0)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving AUTH_TYPE unchanged (BASIC)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving LOGLEVEL unchanged (8482)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving BLOCKLIST_TIMER unchanged (0)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving MAX_PAGES unchanged (0)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving MAX_BOOKPAGES unchanged (0)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving MAX_WALL unchanged (0)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving MATCH_RATIO unchanged (80)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving DLOAD_RATIO unchanged (80)
18-déc.-2021 19:53:13 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving NAME_RATIO unchanged (90)
...
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving GR_UNIQUE unchanged (1)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving GR_FOLLOW unchanged (0)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving GR_FOLLOWNEW unchanged (0)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving GB_API unchanged ()
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving GB_COUNTRY unchanged ()
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving FMT_SERNAME unchanged ($SerName)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving FMT_SERNUM unchanged (Book #$SerNum -$$)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving FMT_SERIES unchanged (( $FmtName $FmtNum ))
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving OPDS_ENABLED unchanged (0)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving OPDS_AUTHENTICATION unchanged (0)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving OPDS_USERNAME unchanged ()
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving OPDS_PASSWORD unchanged ()
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving OPDS_METAINFO unchanged (0)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving OPDS_PAGE unchanged (30)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving RSS_ENABLED unchanged (1)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving RSS_PODCAST unchanged (1)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving RSS_HOST unchanged ()
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving PREF_UNRARLIB unchanged (1)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving USER_AGENT unchanged (Mozilla/5.0 (X11; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving RATESTARS unchanged (1)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving EBOOK_WANTED_FORMATS unchanged (epub, mobi)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving DELETE_OTHER_FORMATS unchanged (0)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving EBOOK_CONVERT unchanged (ebook-convert)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving KEEP_OPF unchanged (1)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving KEEP_JPG unchanged (1)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving FFMPEG unchanged (ffmpeg)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving FFMPEG_OUT unchanged ()
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving AUDIO_OPTIONS unchanged (-ab, 320k)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving CREATE_SINGLEAUDIO unchanged (0)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving KEEP_SEPARATEAUDIO unchanged (0)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving WRITE_AUDIOTAGS unchanged (0)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving ZIP_AUDIOPARTS unchanged (0)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving SWAP_COVERPAGE unchanged (0)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1285 : Leaving SHRINK_MAG unchanged (0)
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1363 : Keep Torznab1
18-déc.-2021 19:53:15 - DEBUG   :: CONFIG_WRITE : __init__.py:config_write:1368 : No section [Torznab1]
18-déc.-2021 19:53:15 - INFO    :: CONFIG_WRITE : __init__.py:config_write:1650 : Config file [/home/odroid/.lazylibrarian/config.ini] Torznab has been updated```

**Comment by skuizy** [comment] 2021-12-18 19:26
Sending Prowlarr API command to LL via my browser gives the following result :
```
{"Success": true, "Data": "Added Torznab [host,prov_apikey,enabled,categories] Invalid parameters [name,providertype]", "Error": {"Code": 200, "Message": "OK"}}
```

Looks like Prowlarr should be using `altername` instead of `name`.
I think the `providertype` listed in invalid parameters list is a bub from LL api.

**Comment by philborman** [comment] 2021-12-18 22:14
LL is expecting dispname or altername (internally LL uses dispname, mylar uses altername)
I can easily add code in LL  to treat "name" as "dispname" to work around this. The "name" parameter is internal use only as it changes when providers are added or removed.

**Comment by skuizy** [comment] 2021-12-19 11:14
Thanks, just tried LL with latest commit, and it works most of the time but there's still something going on on Prowlarr side as sometimes the `name` still gets `TroznabX`. I'm not sure when it hapens yet...

**Comment by philborman** [comment] 2021-12-19 11:18
Can you open a ticket on LL site and post logs there. Its easier/quicker to add a workaround in LL if we can figure out what's going on, or at least pin down exactly what to change in prowlarr

**Comment by skuizy** [comment] 2021-12-19 16:35
I don't think this behaviour comes from LL as it happens when sync is triggered even without any indexer configured in LL. Here are the relevents logs from Prowlarr and LL. You can see that Abnormal is added in LL as Torznab2.
[lazylibrarian.log](https://github.com/Prowlarr/Prowlarr/files/7741158/lazylibrarian.log)
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/7741159/prowlarr.trace.txt)
.

**Comment by Qstick** [comment] 2022-01-03 03:47
> Can you open a ticket on LL site and post logs there. Its easier/quicker to add a workaround in LL if we can figure out what's going on, or at least pin down exactly what to change in prowlarr. There are two possible api calls, one to add a new provider, another to change an existing one. If prowlarr does not provide a name the default is for LL to use TorznabX, the LL log of api calls should show what is being sent to LL and which api call was used

This seems to be worked around in LL now? Anything we need to do? Spinning up the latest LL docker, Prowlarr was able to add and then sync indexers to it.

**Comment by philborman** [comment] 2022-01-03 08:35
The name is now correctly picked up, but the op says he sometimes gets a name sent s "Torznab2" when he is expecting prowlarr to send ”Abnormal (prowlarr)"
I have not been able to reproduce this

**Comment by Qstick** [comment] 2022-01-03 16:12
Thanks, neither can I

**Closed** 2022-01-04 03:20 UTC
Labels: Type: Bug, Area: Applications
