### ISSUE TITLE
[FEAT]:  A column for VIP Expirty

### ISSUE THREAD

**Issue by nigelwarning** [Prowlarr/Prowlarr#508] opened 2021-09-18 09:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

No it is not a problem

### Describe the solution you'd like

So, In stead of having to open a Indexer to see the VIP expirty date. I would love to see a column, like NZBHydra2 with the VIP expiry data in the column like the picture.

![2021-09-18_11-03](https://user-images.githubusercontent.com/51288761/133883384-fa1a54e2-3b7f-4c5a-a5c7-f15e6bf343c6.png)

### Describe alternatives you've considered

Haven't, because they option isn't there yet. 

### Anything else?

I haven't have anything else. Thanks for the great work btw!

[AB#1594](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1594)

**Comment by bakerboy448** [comment] 2021-09-27 16:45
Duplicate of https://github.com/Prowlarr/Prowlarr/issues/456

please try to search a bit better next time

**Closed by bakerboy448** 2021-09-27 16:45 UTC
Labels: Type: Feature Request, Status: Needs Triage
