### ISSUE TITLE
Selecting Chinese UI interface is invalid

### ISSUE THREAD

**Issue by zpengcom** [Prowlarr/Prowlarr#999] opened 2022-05-13 07:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Selecting Chinese UI interface is invalid
![image](https://user-images.githubusercontent.com/8217132/168234402-f41d911a-387c-42e6-bf63-e41cda275965.png)

### Expected Behavior

is radarr
![image](https://user-images.githubusercontent.com/8217132/168235023-163908ad-fa8a-4e06-b657-3c74ece95538.png)

### Environment

```markdown
- OS: DSM
- Prowlarr:0.3.0.1730
- Docker Install:yes
- Using Reverse Proxy:no
- Browser:yes
```

### What branch are you running?

Develop

### Trace Logs?

Missing translation/culture resource: /app/prowlarr/bin/Localization/Core/zh.json

[AB#3141](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3141)

**Comment by bakerboy448** [comment] 2022-05-13 12:45
Duplicate of #975

**Closed** 2022-05-13 22:49 UTC
Labels: Type: Bug, Area: UI, Status: Confirmed
