### ISSUE TITLE
Advanced search

### ISSUE THREAD

**Issue by JediMaster25** [Prowlarr/Prowlarr#1200] opened 2022-11-16 19:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

This feature request isn't related to a problem.

### Describe the solution you'd like

I don't mind how it's implemented.

### Describe alternatives you've considered

I haven't considered any alternatives.

### Anything else?

Nothing else to add.

[AB#4089](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4089)

**Comment by JediMaster25** [comment] 2022-11-16 19:57
Could you add advanced search to filter torrents?

Some filters I have in mind are size, date, number of seeders.

**Comment by bakerboy448** [comment] 2022-11-16 20:08
>  I have searched the existing open and closed issues

Don't just check boxes.  your comment is also what should be in the GHI. The GHI as-is is not valid.

Duplicate of #27

**Comment by bakerboy448** [comment] 2022-11-16 20:08
0

**Closed by bakerboy448** 2022-11-16 20:08 UTC
Labels: Type: Feature Request, Status: Needs Triage
