### ISSUE TITLE
Add multiple public indexers at once rather than individually

### ISSUE THREAD

**Issue by HeroponRikiBestest** [Prowlarr/Prowlarr#1599] opened 2023-04-11 09:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No.

### Describe the solution you'd like

I would like some means of adding multiple public indexers at once rather than manually one-by-one. The solution I'm thinking of would be having check boxes next to all public indexers, and allowing the user to select the ones they want and then allow the user to either select a button for test all or add all. I can't think of a reason why this wouldn't work, but if for whatever reason this specific implementation isn't in line with prowlarr's goals, I would be open to really anything that makes the process of adding more than one public indexer easier.

### Describe alternatives you've considered

Trying to add jackett as an indexer and using the multi-select there,, but I'm aware the FAQ states that adding jackett via /all should not be used, and is deprecated anyways.

### Anything else?

I understand that this has a closed issue with https://github.com/Prowlarr/Prowlarr/issues/407, but as far as I can tell, the person who created the issue closed it randomly without reason rather than any Prowlarr developer deciding to close it.

**Comment by bakerboy448** [comment] 2023-04-11 12:17
Duplicate of #1017
Duplicate of #407
Likely several others as well

There is not really use case for adding a ton public indexers.   Public sites scrape each other and you don't need more than a handful of them before they become redundant.

jackett's /all endpoint provides 0 benefits and only problems and should never be used for anything.

**Closed by bakerboy448** 2023-04-11 12:17 UTC
Labels: Type: Feature Request, Status: Needs Triage
